UPDATE admin_roadmap_items
SET
  summary = 'Privacy-safe analytics event capture, session-idempotent funnel page-view beacons with deterministic variant and normalized source attribution evidence, deterministic seeded experiment assignment, aggregate funnel conversion reports, attribution boundaries, and source-linked reporting.',
  public_evidence_json = '["Tracked by issue #18.", "Issue #87 adds the first /analytics/source-data contract and /analytics/indie-launch-dashboard preview scaffold.", "Issue #105 adds POST /api/analytics/events with seeded event validation, idempotency, hashed request evidence, and aggregate-only source-data reporting.", "Issue #107 adds POST /api/analytics/assignments with seeded experiment validation, deterministic weighted variant assignment, hashed visitor evidence, and aggregate-only assignment reporting.", "Issue #119 adds aggregate funnel conversion report rows from captured test events without exposing raw analytics rows.", "Issue #121 adds browser-side funnel page-view beacons with server-side bot and preview suppression.", "Issue #123 attaches deterministic seeded assignment evidence to captured funnel page views and exposes aggregate variant counts.", "Issue #125 attaches normalized UTM/source attribution to captured funnel page views and exposes aggregate source counts."]',
  next_milestone = 'Add landing-page attribution breakdowns to the analytics dashboard preview without exposing raw event rows.',
  updated_at = unixepoch()
WHERE id = 'roadmap-analytics-testing';

UPDATE admin_user_journeys
SET
  issue_numbers_json = '[18,87,105,107,119,121,123,125]',
  user_goal = 'Inspect seeded analytics definitions, capture privacy-safe test events, record browser-side funnel page views with deterministic variant and source attribution evidence, assign deterministic variants, and read aggregate conversion report rows before cookies, contact-level reporting, or automated decisions exist.',
  source_evidence_json = '["https://bumpgrade.com/analytics/source-data","https://bumpgrade.com/analytics/indie-launch-dashboard","https://bumpgrade.com/api/analytics/events","https://bumpgrade.com/api/analytics/assignments","https://bumpgrade.com/funnels/source-data","https://bumpgrade.com/funnels/indie-launch-sandbox","https://github.com/markitics/bumpgrade/issues/18","https://github.com/markitics/bumpgrade/issues/87","https://github.com/markitics/bumpgrade/issues/105","https://github.com/markitics/bumpgrade/issues/107","https://github.com/markitics/bumpgrade/issues/119","https://github.com/markitics/bumpgrade/issues/121","https://github.com/markitics/bumpgrade/issues/123","https://github.com/markitics/bumpgrade/issues/125"]',
  happy_path_json = '["Fetch /analytics/source-data.","Find event IDs, page-view beacon boundary, aggregate source attribution counts, aggregate variant event counts, metric IDs, aggregate event counts, aggregate conversion report rows, experiment IDs, variant IDs, assignment rule, assignment API, and write boundary.","Open /funnels/indie-launch-sandbox with safe UTM parameters and let the session-idempotent page-view beacon assign a variant and record a seeded event with that variant ID and normalized source attribution.","POST a seeded event to /api/analytics/events with an idempotency key and source route.","POST a seeded experiment assignment to /api/analytics/assignments with an anonymous assignment key, idempotency key, and source route.","Confirm duplicate idempotency returns the same public-safe event or assignment without duplicating rows.","Open /analytics/indie-launch-dashboard to inspect the public preview and caveats."]',
  edge_cases_json = '["Public source-data exposes aggregate counts, aggregate source attribution counts, aggregate variant counts, and conversion rows only, not raw event or assignment rows.","Unsupported event IDs, experiment IDs, source routes, missing idempotency keys, and missing assignment keys return public-safe validation errors.","Bot, crawler, and preview/test-suppressed page-view traffic is ignored before analytics event rows are created.","Cookie assignment, contact-level analytics, raw referrer/query reporting, experiment traffic changes, automated winners, and revenue claims require future confirmed-write APIs.","Agents must include sample-size caveats and must not call sparse test events or assignments statistically meaningful."]',
  agent_access = 'Agents can read /analytics/source-data, event capture boundaries, page-view beacon boundaries, aggregate source attribution evidence, aggregate variant evidence, assignment boundaries, and aggregate conversion report rows. Direct agent analytics writes, custom events, raw campaign/referrer reporting, experiment routing, and automated decisions require future authenticated confirmed-write APIs with privacy review, idempotency, stale-state checks, audit correlation, redaction, retention limits, and sample-size caveats.',
  validation_json = '["Playwright covers /analytics/source-data, /analytics/indie-launch-dashboard, event ingestion, page-view beacon capture with variant and source attribution evidence, bot suppression, assignment ingestion, conversion reporting from captured events, duplicate idempotency, deterministic assignment, validation failures, opt-in event recording, sitemap discovery, and agent manifest discovery.","Issues #87, #105, #107, #119, #121, #123, and #125 record the analytics source-data scaffold, first privacy-safe event capture path, first deterministic assignment path, first aggregate conversion report, first browser-side funnel page-view beacon, first variant-linked page-view evidence, and first aggregate source attribution evidence."]',
  updated_at = unixepoch()
WHERE id = 'journey-publisher-previews-analytics-experiments';

UPDATE admin_user_journeys
SET
  issue_numbers_json = '[18,87,105,107,119,121,123,125]',
  source_evidence_json = '["https://bumpgrade.com/analytics/source-data","https://bumpgrade.com/analytics/indie-launch-dashboard","https://github.com/markitics/bumpgrade/issues/18","https://github.com/markitics/bumpgrade/issues/119","https://github.com/markitics/bumpgrade/issues/121","https://github.com/markitics/bumpgrade/issues/123","https://github.com/markitics/bumpgrade/issues/125"]',
  happy_path_json = '["Capture seeded analytics events with idempotency or visit the public funnel preview to assign a seeded variant and emit a session-idempotent page-view event with variant and source attribution evidence.","Fetch /analytics/source-data.","Read funnelConversionReport rows for metric ID, step ID, visitor count, conversion count, conversion rate, report mode, and sample-size caveat.","Open /analytics/indie-launch-dashboard and confirm the report renders captured rows when samples exist."]',
  edge_cases_json = '["Duplicate idempotency does not inflate conversion counts.","Bot and preview/test-suppressed page-view traffic is ignored before it can inflate visitor counts.","Rows fall back to fixture counts only when no captured samples exist.","Raw analytics rows, full referrers, raw query strings, IP hashes, user agent hashes, visitor keys, contact IDs, and Stripe IDs are not included.","Sparse samples are not statistically meaningful and must be labeled with caveats."]',
  agent_access = 'Agents can read aggregate funnel conversion rows and cite metric IDs, event IDs, aggregate source attribution evidence, aggregate variant evidence, and issues #119/#121/#123/#125 evidence. Direct analytics writes, raw referrer/query reporting, traffic routing, and automated experiment decisions require future confirmed-write APIs.',
  validation_json = '["Playwright seeds captured events, visits the funnel page-view beacon, replays duplicate idempotency, verifies aggregate source and variant counts, verifies conversion counts and rates, and checks public source-data excludes raw/private rows.","Issues #119, #121, #123, and #125 record the aggregate conversion report, browser-side funnel page-view instrumentation, variant-linked page-view evidence, and source-attributed page-view evidence."]',
  updated_at = unixepoch()
WHERE id = 'journey-publisher-reads-funnel-conversion-report';

UPDATE admin_user_journeys
SET
  issue_numbers_json = '[18,87,105,121,125]',
  source_evidence_json = '["https://bumpgrade.com/api/analytics/events","https://bumpgrade.com/analytics/source-data","https://github.com/markitics/bumpgrade/issues/18","https://github.com/markitics/bumpgrade/issues/87","https://github.com/markitics/bumpgrade/issues/105","https://github.com/markitics/bumpgrade/issues/121","https://github.com/markitics/bumpgrade/issues/125"]',
  edge_cases_json = '["Missing idempotency is rejected.","Unsupported event IDs and source routes are rejected.","Known bot/crawler and explicit preview/test-suppressed traffic returns an ignored public-safe response without adding analytics event rows.","Private request fields are hashed or omitted.","The API does not create cookies, store raw campaign/referrer payloads, route experiment traffic, or decide winners."]',
  agent_access = 'Agents can inspect the event capture contract and propose seeded analytics events with normalized public properties, but direct agent analytics writes beyond seeded events and raw attribution access require future authenticated confirmed-write APIs.',
  validation_json = '["Playwright covers valid event ingestion, bot/crawler suppression, duplicate idempotency, validation failures, normalized source attribution, and aggregate-only source-data.","Issues #105, #121, and #125 record the first live analytics event capture path, first bot-suppressed browser beacon path, and normalized source attribution boundary."]',
  updated_at = unixepoch()
WHERE id = 'journey-agent-records-privacy-safe-analytics-event';
