CREATE TABLE IF NOT EXISTS product_asset_uploads (
  id TEXT PRIMARY KEY,
  idempotency_key TEXT NOT NULL,
  actor_user_id TEXT,
  actor_email_hash TEXT NOT NULL,
  actor_role TEXT NOT NULL,
  product_id TEXT NOT NULL,
  asset_id TEXT NOT NULL,
  file_name TEXT NOT NULL,
  content_type TEXT NOT NULL,
  byte_count INTEGER NOT NULL,
  body_sha256 TEXT NOT NULL,
  r2_object_key TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'stored_private',
  confirmation_text_sha256 TEXT NOT NULL,
  metadata_json TEXT,
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at INTEGER NOT NULL DEFAULT (unixepoch())
);

CREATE UNIQUE INDEX IF NOT EXISTS product_asset_uploads_idempotency_unique
  ON product_asset_uploads(idempotency_key);
CREATE INDEX IF NOT EXISTS product_asset_uploads_product_asset_status_idx
  ON product_asset_uploads(product_id, asset_id, status);
CREATE INDEX IF NOT EXISTS product_asset_uploads_created_idx
  ON product_asset_uploads(created_at);

UPDATE admin_roadmap_items
SET
  summary = 'Digital product records, product/access source data, sandbox webhook-backed entitlement grants, owner entitlement inspection, customer entitlement lookup, private R2-backed fixture delivery with redemption revalidation, owner-confirmed private asset upload intents, fulfillment task evidence, protected content planning, access rules, and subscriptions.',
  public_evidence_json = '["Tracked by issue #16.", "Issue #83 adds the first /products/source-data contract and /products/indie-launch-library preview scaffold.", "Issue #101 adds idempotent sandbox entitlement rows and fulfillment task evidence from trusted paid checkout webhook events.", "Issue #139 adds /admin/products owner entitlement inspection and aggregate public redaction flags.", "Issue #141 adds /products/entitlements and /api/products/entitlements for customer-safe checkout intent entitlement lookup.", "Issue #143 adds one-use download tokens for active file entitlements without exposing private R2 keys or signed object URLs.", "Issue #146 adds a seeded private R2-backed fixture delivery path through one-use Bumpgrade tokens.", "Issue #147 revalidates current entitlement status, checkout intent linkage, trusted checkout state, and asset scope before token redemption.", "Issue #151 adds owner-confirmed private product asset upload records backed by PRODUCT_ASSETS without exposing object keys, signed URLs, upload bodies, or private metadata."]',
  next_milestone = 'Connect owner-uploaded private assets to customer delivery while preserving the same token, entitlement, expiry, stale-state, and redaction boundaries.',
  updated_at = unixepoch()
WHERE id = 'roadmap-products-access';

UPDATE admin_user_journeys
SET
  issue_numbers_json = '[16,83,101,139,141,143,146,147,151]',
  source_evidence_json = '["https://bumpgrade.com/products/source-data","https://bumpgrade.com/products/indie-launch-library","https://bumpgrade.com/products/entitlements","https://bumpgrade.com/api/products/entitlements","https://bumpgrade.com/api/products/download-tokens","https://bumpgrade.com/api/products/downloads?token={token}","https://bumpgrade.com/api/admin/products/assets","https://bumpgrade.com/admin/products","https://bumpgrade.com/offers/source-data","https://github.com/markitics/bumpgrade/issues/16","https://github.com/markitics/bumpgrade/issues/83","https://github.com/markitics/bumpgrade/issues/101","https://github.com/markitics/bumpgrade/issues/139","https://github.com/markitics/bumpgrade/issues/141","https://github.com/markitics/bumpgrade/issues/143","https://github.com/markitics/bumpgrade/issues/146","https://github.com/markitics/bumpgrade/issues/147","https://github.com/markitics/bumpgrade/issues/151"]',
  happy_path_json = '["Fetch /products/source-data.","Find seeded product types, asset IDs, access rules, entitlement templates, sandbox grant mappings, aggregate entitlement inspection counts, customer lookup contract, private R2-backed delivery contract, owner-upload intent contract, revision ID, and write boundary.","Open /products/indie-launch-library to inspect the public preview.","Open /admin/products as a verified owner to inspect private buyer entitlement rows, checkout state, product/price context, and queued fulfillment evidence.","Open /products/entitlements with a checkout intent reference to inspect customer-safe entitlement and fulfillment state.","Create and consume a short-lived download token for an active file entitlement after current entitlement and trusted checkout state are revalidated, streaming the seeded private R2-backed fixture through Bumpgrade without exposing private R2 keys or signed object URLs.","As a verified owner, create a small private product asset upload record only after exact confirmation, idempotency, and catalog revision checks.","Use /offers/source-data and /commerce/source-data to confirm checkout and webhook dependencies before assuming fulfillment exists."]',
  edge_cases_json = '["The seeded product/access catalog is not a complete product admin.","Public /products/source-data exposes aggregate entitlement and owner-upload counts plus redaction flags, not buyer emails, raw Stripe IDs, hashes, metadata JSON, R2 keys, signed URLs, or upload bodies.","A token is rejected without being consumed when current entitlement or trusted checkout state is no longer eligible.","Owner-uploaded private assets are stored as records but are not yet wired to customer delivery.","Signed object URLs, protected lessons, revocation, customer delivery of arbitrary uploads, and live fulfillment automation require future confirmed-write APIs.","Subscription access requires trusted billing state before membership entitlements can be granted."]',
  agent_access = 'Agents can read /products/source-data, aggregate entitlement inspection counts, the preview route, the customer-safe checkout intent lookup contract, the short-lived private R2-backed download-token boundary with redemption revalidation, and the owner-authenticated private asset upload intent boundary. Owner sessions can inspect private buyer entitlement rows in /admin/products and can create small private asset upload records only through exact-confirmed, idempotent, revision-checked writes. Trusted paid sandbox webhooks can grant seeded entitlement rows; direct customer delivery of arbitrary uploads, revocation, and protected content require later APIs.',
  validation_json = '["Playwright covers /products/source-data, aggregate entitlement inspection redaction, /products/indie-launch-library, customer /products/entitlements lookup, private R2-backed token delivery, current checkout-state revalidation, replay rejection, owner /admin/products inspection, owner private asset upload intent creation, idempotent replay, unauthorized rejection, public redaction, sitemap discovery, and agent manifest read-contract discovery.","Issue #83 records the first product/access source-data contract and preview scaffold.","Issue #101 records the first sandbox webhook-backed entitlement grant path.","Issue #139 records the owner product entitlement inspection path.","Issue #141 records the customer-safe product entitlement lookup path.","Issue #143 records the short-lived download-token path.","Issue #146 records the seeded private R2-backed fixture delivery path.","Issue #147 records token redemption revalidation against current entitlement and trusted checkout state.","Issue #151 records the owner-confirmed private product asset upload intent path."]',
  updated_at = unixepoch()
WHERE id = 'journey-publisher-previews-product-access';

UPDATE admin_user_journeys
SET
  issue_numbers_json = '[16,83,99,101,139,141,143,146,147,151]',
  source_evidence_json = '["https://bumpgrade.com/products/source-data","https://bumpgrade.com/products/entitlements","https://bumpgrade.com/api/products/entitlements","https://bumpgrade.com/api/products/download-tokens","https://bumpgrade.com/api/products/downloads?token={token}","https://bumpgrade.com/api/admin/products/assets","https://bumpgrade.com/admin/products","https://bumpgrade.com/commerce/source-data","https://bumpgrade.com/offers/source-data","https://github.com/markitics/bumpgrade/issues/16","https://github.com/markitics/bumpgrade/issues/99","https://github.com/markitics/bumpgrade/issues/101","https://github.com/markitics/bumpgrade/issues/139","https://github.com/markitics/bumpgrade/issues/141","https://github.com/markitics/bumpgrade/issues/143","https://github.com/markitics/bumpgrade/issues/146","https://github.com/markitics/bumpgrade/issues/147","https://github.com/markitics/bumpgrade/issues/151"]',
  happy_path_json = '["Start a sandbox checkout for the primary offer and selected order bump.","Receive trusted checkout.session.completed webhook evidence.","Update the checkout intent to paid.","Insert idempotent product_entitlements rows for mapped line items.","Queue public-safe fulfillment task evidence without returning signed URLs, R2 object keys, or private buyer data.","Open /products/entitlements with the checkout intent reference to confirm customer-safe entitlement and fulfillment status.","Create and consume a one-use download token that revalidates current entitlement and trusted checkout state before streaming the seeded private R2-backed fixture for a file entitlement.","As a verified owner, create a small private upload record for the file asset after exact confirmation, idempotency, and catalog revision checks.","Open /admin/products as a verified owner to inspect the entitlement rows and queued fulfillment evidence."]',
  edge_cases_json = '["Duplicate webhook events do not create duplicate entitlements.","Public /products/source-data exposes aggregate counts and redaction flags, not raw buyer rows.","A token created before a checkout state change is rejected while checkout state is no longer trusted paid or completed.","Owner-uploaded private assets are not yet customer-delivered.","Revocation, signed downloads, protected content, customer portal, refunds, and direct customer delivery of arbitrary uploads require later confirmed-write APIs.","Raw Stripe identifiers and buyer email remain server-private."]',
  agent_access = 'Agents can read /products/source-data, /api/products/entitlements, /api/products/download-tokens, and /commerce/source-data to understand the entitlement grant contract, customer-safe lookup, short-lived private R2-backed fixture delivery with redemption revalidation, owner-upload intent boundary, and aggregate inspection counts. Owner sessions can inspect private buyer entitlement rows in /admin/products and create small private asset upload records via exact-confirmed, idempotent, revision-checked writes. Agents cannot grant, revoke, expose private buyer data, deliver arbitrary uploads to customers, or issue signed object URLs without future authenticated confirmed-write APIs.',
  validation_json = '["Playwright covers source-data output, aggregate redaction, a paid test checkout webhook that creates entitlement rows, customer-safe lookup, private R2-backed token delivery, current checkout-state revalidation, replay rejection, owner private asset upload intent creation, idempotent replay, unauthorized rejection, owner /admin/products inspection, and duplicate webhook idempotency.","Issue #101 records the sandbox entitlement grant path.","Issue #139 records the owner product entitlement inspection path.","Issue #141 records the customer-safe product entitlement lookup path.","Issue #143 records the short-lived download-token path.","Issue #146 records the seeded private R2-backed fixture delivery path.","Issue #147 records token redemption revalidation against current entitlement and trusted checkout state.","Issue #151 records the owner-confirmed private product asset upload intent path."]',
  updated_at = unixepoch()
WHERE id = 'journey-publisher-verifies-sandbox-entitlement-grant';
