UPDATE admin_roadmap_items
SET
  status = 'active',
  summary = 'Shared mobile-admin contract, live public-safe dashboard source-data, plus first iOS simulator and Android emulator scaffolds for independently shippable mobile app slices.',
  public_evidence_json = '["Issue #13 owns the shared mobile admin contract.", "Issue #67 adds the first iOS Expo entrypoint, generated fixture, simulator target, validation command, smoke command, and screenshot path.", "Issue #68 adds the first native Android activity, generated fixture asset, emulator target, validation command, smoke command, and screenshot path.", "Issue #153 adds /mobile-admin/dashboard/source-data as the live public-safe dashboard contract.", "/mobile-admin/source-data exposes the shared mobile contract.", "/mobile-admin/dashboard/source-data exposes the public-safe dashboard digest for mobile clients.", "/mobile-admin/ios/source-data exposes the iOS scaffold and smoke metadata.", "/mobile-admin/android/source-data exposes the Android scaffold and smoke metadata."]',
  next_milestone = 'Wire iOS and Android clients to the live dashboard route, then add mobile auth and confirmed-write UX in follow-up slices.',
  mark_attention = NULL,
  updated_at = unixepoch()
WHERE id = 'roadmap-mobile-admin';

UPDATE admin_user_journeys
SET
  issue_numbers_json = '[13,67,68,153]',
  source_evidence_json = '["https://bumpgrade.com/mobile-admin/source-data","https://bumpgrade.com/mobile-admin/dashboard/source-data","https://bumpgrade.com/mobile-admin/ios/source-data","https://bumpgrade.com/mobile-admin/android/source-data","https://bumpgrade.com/agent-docs/bumpgrade-mobile-admin","https://github.com/markitics/bumpgrade/issues/13","https://github.com/markitics/bumpgrade/issues/67","https://github.com/markitics/bumpgrade/issues/68","https://github.com/markitics/bumpgrade/issues/153"]',
  happy_path_json = '["Open the future mobile admin app.","Fetch /mobile-admin/dashboard/source-data for the public-safe mobile dashboard digest.","For iOS, open the first simulator scaffold and read the digest sourced from the generated /mobile-admin/source-data fixture.","For Android, open the first emulator scaffold and read the digest sourced from the same generated /mobile-admin/source-data fixture.","Use the dashboard digest to resolve live /admin/source-data, /features/source-data, /roadmap/source-data, /commerce/source-data, and /agent-docs/source-data without scraping private admin pages.","Review work-log entries, for-Mark attention, and checkout health.","Follow iOS issue #67, Android issue #68, or dashboard issue #153 for implementation evidence."]',
  edge_cases_json = '["The iOS simulator target is not App Store distribution, push notifications, private mobile auth, or confirmed-write support.","The Android emulator target is not Play Store distribution, push notifications, private mobile auth, or confirmed-write support.","Private admin state requires Better Auth owner or publisher sessions.","Mobile writes stay disabled until confirmed-write APIs exist.","/mobile-admin/dashboard/source-data is public-safe and excludes private buyer rows, owner email values, raw inbox bodies, R2 object keys, signed URLs, secret values, upload bodies, session IDs, and write tokens."]',
  agent_access = 'Agents can read /mobile-admin/source-data, /mobile-admin/dashboard/source-data, /mobile-admin/ios/source-data, and /mobile-admin/android/source-data to understand app scope, live public-safe mobile digest state, and smoke evidence; they must not claim mobile app parity until private auth, distribution, and confirmed writes ship.',
  validation_json = '["Issue #13 defines the shared contract and splits iOS and Android child issues.","Issue #67 adds an Expo app scaffold, generated fixture, iOS simulator target, validation command, smoke command, and screenshot path.","Issue #68 adds a native Android activity, generated fixture asset, emulator target, validation command, smoke command, and screenshot path.","Issue #153 adds /mobile-admin/dashboard/source-data as the live public-safe dashboard contract.","Playwright covers /agent-docs/bumpgrade-mobile-admin, /mobile-admin/source-data, /mobile-admin/dashboard/source-data, /mobile-admin/ios/source-data, and /mobile-admin/android/source-data."]',
  updated_at = unixepoch()
WHERE id = 'journey-publisher-checks-mobile-admin';
