UPDATE admin_roadmap_items
SET
  summary = 'Shared mobile-admin contract, live public-safe dashboard source-data, plus iOS, Android, and Expo scaffolds that render the dashboard route from the generated fixture.',
  public_evidence_json = '["Issue #13 owns the shared mobile admin contract.", "Issue #67 adds the first iOS Expo entrypoint, generated fixture, simulator target, validation command, smoke command, and screenshot path.", "Issue #68 adds the first native Android activity, generated fixture asset, emulator target, validation command, smoke command, and screenshot path.", "Issue #153 adds /mobile-admin/dashboard/source-data as the live public-safe dashboard contract.", "Issue #155 renders the live dashboard route and redaction boundary in the Expo, iOS, and Android scaffold surfaces.", "/mobile-admin/source-data exposes the shared mobile contract.", "/mobile-admin/dashboard/source-data exposes the public-safe dashboard digest for mobile clients.", "/mobile-admin/ios/source-data exposes the iOS scaffold and smoke metadata.", "/mobile-admin/android/source-data exposes the Android scaffold and smoke metadata."]',
  next_milestone = 'Replace fixture-only dashboard hydration with live network reads, then add mobile auth and confirmed-write UX in follow-up slices.',
  updated_at = unixepoch()
WHERE id = 'roadmap-mobile-admin';

UPDATE admin_user_journeys
SET
  issue_numbers_json = '[13,67,68,153,155]',
  source_evidence_json = '["https://bumpgrade.com/mobile-admin/source-data","https://bumpgrade.com/mobile-admin/dashboard/source-data","https://bumpgrade.com/mobile-admin/ios/source-data","https://bumpgrade.com/mobile-admin/android/source-data","https://bumpgrade.com/agent-docs/bumpgrade-mobile-admin","https://github.com/markitics/bumpgrade/issues/13","https://github.com/markitics/bumpgrade/issues/67","https://github.com/markitics/bumpgrade/issues/68","https://github.com/markitics/bumpgrade/issues/153","https://github.com/markitics/bumpgrade/issues/155"]',
  happy_path_json = '["Open the future mobile admin app.","Fetch /mobile-admin/dashboard/source-data for the public-safe mobile dashboard digest.","For iOS, open the first simulator scaffold and read the digest sourced from the generated /mobile-admin/source-data fixture.","For Android, open the first emulator scaffold and read the digest sourced from the same generated /mobile-admin/source-data fixture.","Confirm the Expo, iOS, and Android surfaces render the live dashboard route, status, issue, and redaction boundary from the generated fixture.","Use the dashboard digest to resolve live /admin/source-data, /features/source-data, /roadmap/source-data, /commerce/source-data, and /agent-docs/source-data without scraping private admin pages.","Review work-log entries, for-Mark attention, and checkout health.","Follow iOS issue #67, Android issue #68, dashboard issue #153, or scaffold rendering issue #155 for implementation evidence."]',
  validation_json = '["Issue #13 defines the shared contract and splits iOS and Android child issues.","Issue #67 adds an Expo app scaffold, generated fixture, iOS simulator target, validation command, smoke command, and screenshot path.","Issue #68 adds a native Android activity, generated fixture asset, emulator target, validation command, smoke command, and screenshot path.","Issue #153 adds /mobile-admin/dashboard/source-data as the live public-safe dashboard contract.","Issue #155 renders the live dashboard route and redaction boundary in the Expo, iOS, and Android scaffold surfaces.","Playwright covers /agent-docs/bumpgrade-mobile-admin, /mobile-admin/source-data, /mobile-admin/dashboard/source-data, /mobile-admin/ios/source-data, and /mobile-admin/android/source-data. Mobile validations assert the scaffold apps render the live dashboard panel."]',
  updated_at = unixepoch()
WHERE id = 'journey-publisher-checks-mobile-admin';
