UPDATE admin_roadmap_items
SET
  summary = 'Shared mobile-admin contract, live public-safe dashboard source-data, plus iOS, Android, and Expo scaffolds that live-read the dashboard route with fixture fallback.',
  public_evidence_json = '["Tracked by issue #13.", "iOS app slice tracked by issue #67.", "Android app slice tracked by issue #68.", "Live dashboard source-data slice tracked by issue #153.", "Mobile dashboard scaffold rendering tracked by issue #155.", "Mobile dashboard live network hydration tracked by issue #157.", "`/mobile-admin/source-data` exposes the shared mobile contract and no-installable-app caveat.", "`/mobile-admin/dashboard/source-data` exposes the public-safe dashboard digest for mobile clients.", "`/mobile-admin/ios/source-data` exposes the iOS scaffold, fixture fallback, live dashboard URL, simulator smoke command, and screenshot path.", "`/mobile-admin/android/source-data` exposes the Android scaffold, fixture fallback, live dashboard URL, emulator smoke command, and screenshot path."]',
  next_milestone = 'Add mobile auth and confirmed-write UX in follow-up slices after the read-only live dashboard stabilizes.',
  updated_at = unixepoch()
WHERE id = 'roadmap-mobile-admin';

UPDATE admin_user_journeys
SET
  issue_numbers_json = '[13,67,68,153,155,157]',
  source_evidence_json = '["https://bumpgrade.com/mobile-admin/source-data","https://bumpgrade.com/mobile-admin/dashboard/source-data","https://bumpgrade.com/mobile-admin/ios/source-data","https://bumpgrade.com/mobile-admin/android/source-data","https://bumpgrade.com/agent-docs/bumpgrade-mobile-admin","https://github.com/markitics/bumpgrade/issues/13","https://github.com/markitics/bumpgrade/issues/67","https://github.com/markitics/bumpgrade/issues/68","https://github.com/markitics/bumpgrade/issues/153","https://github.com/markitics/bumpgrade/issues/155","https://github.com/markitics/bumpgrade/issues/157"]',
  happy_path_json = '["Open the future mobile admin app.","Fetch /mobile-admin/dashboard/source-data for the public-safe mobile dashboard digest.","For iOS, open the first simulator scaffold and read the live dashboard payload, falling back to the generated fixture if the network is unavailable.","For Android, open the first emulator scaffold and read the live dashboard payload, falling back to the same generated fixture if the network is unavailable.","Confirm the Expo, iOS, and Android surfaces distinguish live network hydration from fixture fallback while keeping the dashboard read-only.","Use the dashboard digest to resolve live /admin/source-data, /features/source-data, /roadmap/source-data, /commerce/source-data, and /agent-docs/source-data without scraping private admin pages.","Review work-log entries, for-Mark attention, and checkout health.","Follow iOS issue #67, Android issue #68, dashboard issue #153, scaffold rendering issue #155, or live hydration issue #157 for implementation evidence."]',
  validation_json = '["Issue #13 defines the shared contract and splits iOS and Android child issues.","Issue #67 adds an Expo app scaffold, generated fixture, iOS simulator target, validation command, smoke command, and screenshot path.","Issue #68 adds a native Android activity, generated fixture asset, emulator target, validation command, smoke command, and screenshot path.","Issue #153 adds /mobile-admin/dashboard/source-data as the live public-safe dashboard contract.","Issue #155 renders the live dashboard route and redaction boundary in the Expo, iOS, and Android scaffold surfaces.","Issue #157 fetches the live dashboard route in Expo, iOS, and Android while preserving fixture fallback for deterministic smoke tests.","Playwright covers /agent-docs/bumpgrade-mobile-admin, /mobile-admin/source-data, /mobile-admin/dashboard/source-data, /mobile-admin/ios/source-data, and /mobile-admin/android/source-data. Mobile validations assert the scaffold apps render and live-hydrate the dashboard panel."]',
  updated_at = unixepoch()
WHERE id = 'journey-publisher-checks-mobile-admin';
