UPDATE admin_roadmap_items
SET
  summary = 'Multi-step funnel model, source-data contract, read-only seeded preview scaffold, D1-backed editable draft scaffold with step edit/reorder controls, owner-gated private preview, exact-confirmed public publishing, reusable template and block-template library records, owner-confirmed template-to-draft creation, owner-confirmed checkout-offer linking on private draft steps, and safe draft proposals.',
  public_evidence_json = '["Tracked by issue #14.", "Issue #79 adds the first `/funnels/source-data` contract and `/funnels/indie-launch-sandbox` preview scaffold.", "Issue #91 adds owner-gated `/admin/funnels`, `/api/admin/funnels/drafts`, and D1 draft/audit tables.", "Issue #93 adds owner-gated step title, goal, kind, and order editing on private D1 drafts.", "Issue #95 adds owner-gated private draft preview from current D1 draft state.", "Issue #135 adds exact-confirmed public publishing from D1 draft funnels to stable public `/funnels/{slug}` routes.", "Issue #159 adds reusable funnel templates and block-template library records to `/funnels/source-data` and the seeded preview route.", "Issue #161 adds owner-confirmed template-to-draft creation from reusable funnel templates.", "Issue #163 adds owner-confirmed checkout-offer linking to private draft checkout blocks."]',
  next_milestone = 'Add deletion/archive, unpublishing, drag-and-drop block editing, and direct agent-safe edit tools on top of D1 draft funnels.',
  updated_at = unixepoch()
WHERE id = 'roadmap-funnels';

UPDATE admin_user_journeys
SET
  issue_numbers_json = '[14,79,159,161,163]',
  user_goal = 'Inspect an ordered opt-in, sales, and thank-you funnel plus reusable templates, block records, and owner-session checkout-link capability before visual editing or direct agent template creation exists.',
  source_evidence_json = '["https://bumpgrade.com/funnels/source-data","https://bumpgrade.com/funnels/indie-launch-sandbox","https://github.com/markitics/bumpgrade/issues/14","https://github.com/markitics/bumpgrade/issues/79","https://github.com/markitics/bumpgrade/issues/159","https://github.com/markitics/bumpgrade/issues/161","https://github.com/markitics/bumpgrade/issues/163"]',
  happy_path_json = '["Fetch /funnels/source-data.", "Find the seeded draft funnel, revision ID, ordered step IDs, block IDs, preview route, checkout-linking capability, and write boundary.", "Inspect reusable funnel templates and block-template records, including owner-session draftCreation and block write boundaries.", "Open /funnels/indie-launch-sandbox to inspect semantic preview sections.", "Use the write boundary to avoid claiming unpublish/delete, direct agent checkout-link, or direct agent-write capability."]',
  edge_cases_json = '["The seeded funnel is read-only and not an authenticated builder UI.", "Owner-session template-to-draft creation and checkout-offer linking are available from /admin/funnels, but deletion, unpublishing, and direct agent edits require future confirmed-write APIs.", "Generated copy remains draft until a publisher confirms it."]',
  agent_access = 'Agents can read /funnels/source-data, reusable template and block-template records, checkout-link capability metadata, the seeded preview route, and published D1 funnel routes. Owner-session template-to-draft creation and checkout-offer linking require confirmation and idempotency; direct agent writes require actor identity, confirmation, idempotency, stale-state checks, audit correlation, redaction, and rollback notes.',
  validation_json = '["Playwright covers /funnels/source-data, /funnels/indie-launch-sandbox template and block library rendering, sitemap discovery, and agent manifest read-contract discovery.", "Issue #79 records the first funnel source-data contract and preview scaffold.", "Issue #159 records the first reusable template and block-template library contract.", "Issue #161 records owner-confirmed template-to-draft creation.", "Issue #163 records owner-confirmed checkout-offer linking on private draft steps."]',
  updated_at = unixepoch()
WHERE id = 'journey-publisher-previews-seeded-funnel';

UPDATE admin_user_journeys
SET
  issue_numbers_json = '[14,79,91,93,95,135,159,161,163]',
  user_goal = 'Create, seed, or template-start a D1-backed draft funnel, tune the ordered steps, attach the seeded sandbox checkout offer to a checkout block, preview it privately, then publish it to a public route after exact confirmation.',
  source_evidence_json = '["https://bumpgrade.com/admin/funnels","https://bumpgrade.com/admin/funnels/funnel-draft-indie-launch-working-copy/preview","https://bumpgrade.com/funnels/indie-launch-working-copy","https://bumpgrade.com/funnels/source-data","https://github.com/markitics/bumpgrade/issues/14","https://github.com/markitics/bumpgrade/issues/91","https://github.com/markitics/bumpgrade/issues/93","https://github.com/markitics/bumpgrade/issues/95","https://github.com/markitics/bumpgrade/issues/135","https://github.com/markitics/bumpgrade/issues/159","https://github.com/markitics/bumpgrade/issues/161","https://github.com/markitics/bumpgrade/issues/163"]',
  happy_path_json = '["Sign in with an allowlisted owner account.", "Open /admin/funnels.", "Seed the indie launch working draft, create a generic draft, or create a private draft from a reusable template after typing the exact template confirmation text.", "Edit a step title, goal, or kind, then move a step up or down.", "Attach the seeded sandbox checkout offer to a draft checkout block after typing the exact checkout-link confirmation text and using the current draft revision.", "Open the owner-gated preview route to confirm the private draft sequence reflects current D1 state.", "Type the exact publish confirmation text with the current revision and publish the draft.", "Open the public /funnels/{slug} route and confirm the published sequence is crawlable.", "Use /funnels/source-data to distinguish published D1 funnels from unpublished private drafts."]',
  edge_cases_json = '["The admin draft builder is owner-gated and unpublished draft copy is not crawlable public content.", "Template-to-draft creation writes only private D1 draft rows and audit metadata; it does not publish.", "Checkout-offer linking writes public-safe metadata into private draft step blocks and does not start a checkout session or enable live billing.", "Publishing requires exact confirmation and a fresh revision ID.", "Checkout-link deletion, unpublishing, drag-and-drop layout editing, and direct agent writes still require future confirmed-write APIs.", "/funnels/source-data lists published D1 funnels but does not expose raw owner session or unpublished private draft data."]',
  agent_access = 'Agents can read public /funnels/source-data, seeded funnel routes, reusable templates, checkout-link capability metadata, and published D1 funnel routes. Owner-session UI may create from templates, edit, link checkout offers, preview, and publish private draft steps with actor identity, confirmation, idempotency, audit correlation, stale-state checks, and redaction; direct agent edit tools are still planned.',
  validation_json = '["Playwright covers the owner-gated /admin/funnels surface, template-to-draft create path, checkout-link create path, idempotent replay, stale checkout-link rejection, seed/update/reorder/publish POST paths, stale publish rejection, private draft preview, public D1 funnel route rendering, /funnels/source-data capability metadata, and agent manifest discovery.", "Issue #91 records the first D1-backed draft funnel builder scaffold.", "Issue #93 records the first step edit and reorder controls.", "Issue #95 records the first owner-gated private draft preview route.", "Issue #135 records the first exact-confirmed D1 draft publishing path.", "Issue #159 records reusable template and block-template source data.", "Issue #161 records owner-confirmed template-to-draft creation.", "Issue #163 records owner-confirmed checkout-offer linking on private draft steps."]',
  updated_at = unixepoch()
WHERE id = 'journey-owner-seeds-editable-draft-funnel';
