ALTER TABLE product_entitlement_revocation_intents ADD COLUMN target_entitlement_id TEXT;
ALTER TABLE product_entitlement_revocation_intents ADD COLUMN idempotency_key TEXT;
ALTER TABLE product_entitlement_revocation_intents ADD COLUMN actor_user_id TEXT;
ALTER TABLE product_entitlement_revocation_intents ADD COLUMN actor_email_hash TEXT;
ALTER TABLE product_entitlement_revocation_intents ADD COLUMN actor_role TEXT;
ALTER TABLE product_entitlement_revocation_intents ADD COLUMN expected_entitlement_status TEXT;
ALTER TABLE product_entitlement_revocation_intents ADD COLUMN reason_code TEXT;
ALTER TABLE product_entitlement_revocation_intents ADD COLUMN private_reason_sha256 TEXT;
ALTER TABLE product_entitlement_revocation_intents ADD COLUMN confirmation_text_sha256 TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS product_entitlement_revocation_intents_idempotency_unique
  ON product_entitlement_revocation_intents(idempotency_key)
  WHERE idempotency_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS product_entitlement_revocation_intents_target_idx
  ON product_entitlement_revocation_intents(target_entitlement_id, status);

UPDATE admin_roadmap_items
SET
  summary = 'Digital product records, product/access source data, sandbox webhook-backed entitlement grants, owner entitlement inspection, customer entitlement lookup, private R2-backed fixture delivery with redemption revalidation, owner-confirmed private asset upload intents, owner-confirmed non-destructive revocation intents, protected content readiness, checkout-intent-scoped protected fixture delivery, subscription-backed membership access, fulfillment task evidence, access rules, and subscriptions.',
  public_evidence_json = '["Tracked by issue #16.", "Issue #83 adds the first /products/source-data contract and /products/indie-launch-library preview scaffold.", "Issue #101 adds idempotent sandbox entitlement rows and fulfillment task evidence from trusted paid checkout webhook events.", "Issue #139 adds /admin/products owner entitlement inspection and aggregate public redaction flags.", "Issue #141 adds /products/entitlements and /api/products/entitlements for customer-safe checkout intent entitlement lookup.", "Issue #143 adds one-use download tokens for active file entitlements without exposing private R2 keys or signed object URLs.", "Issue #146 streams a seeded private R2-backed fixture through Bumpgrade without exposing private object keys.", "Issue #147 revalidates current entitlement and trusted checkout state before redemption.", "Issue #151 adds owner-confirmed private product asset upload intent records.", "Issue #179 adds owner-visible revocation intent readiness without destructive entitlement mutation.", "Issue #251 adds owner-confirmed non-destructive revocation intent records with exact confirmation, idempotency, stale-state checks, and public redaction."]',
  next_milestone = 'Add destructive revocation only after customer-safe notification review, refund/dispute policy, audit correlation, and entitlement/billing state checks are enforced together.',
  updated_at = unixepoch()
WHERE id = 'roadmap-products-access';

UPDATE admin_user_journeys
SET
  issue_numbers_json = '[16,83,101,139,141,143,146,147,151,179,181,185,187,251]',
  source_evidence_json = '["https://bumpgrade.com/products/source-data", "https://bumpgrade.com/products/indie-launch-library", "https://bumpgrade.com/products/entitlements", "https://bumpgrade.com/api/products/entitlements", "https://bumpgrade.com/api/products/download-tokens", "https://bumpgrade.com/api/products/protected-content", "https://bumpgrade.com/api/admin/products/assets", "https://bumpgrade.com/api/admin/products/revocation-intents", "https://bumpgrade.com/admin/products", "https://bumpgrade.com/offers/source-data", "https://github.com/markitics/bumpgrade/issues/16", "https://github.com/markitics/bumpgrade/issues/83", "https://github.com/markitics/bumpgrade/issues/101", "https://github.com/markitics/bumpgrade/issues/139", "https://github.com/markitics/bumpgrade/issues/141", "https://github.com/markitics/bumpgrade/issues/143", "https://github.com/markitics/bumpgrade/issues/146", "https://github.com/markitics/bumpgrade/issues/147", "https://github.com/markitics/bumpgrade/issues/151", "https://github.com/markitics/bumpgrade/issues/179", "https://github.com/markitics/bumpgrade/issues/181", "https://github.com/markitics/bumpgrade/issues/185", "https://github.com/markitics/bumpgrade/issues/187", "https://github.com/markitics/bumpgrade/issues/251"]',
  user_goal = 'Inspect products, assets, access rules, entitlement templates, sandbox entitlement grant mappings, subscription-backed membership access, owner entitlement rows, owner-confirmed revocation intents, and protected fixture delivery checks before real private content storage is enabled.',
  happy_path_json = '["Fetch /products/source-data.", "Find seeded product types, asset IDs, access rules, entitlement templates, sandbox grant mappings, subscription membership access contract, aggregate entitlement inspection counts, customer lookup contract, private R2-backed delivery contract, owner-upload intent contract, owner-confirmed revocation intent contract, protected content readiness, protected fixture delivery contract, revision ID, and write boundary.", "Open /products/indie-launch-library to inspect the public preview.", "Open /admin/products as a verified owner to inspect private buyer entitlement rows, checkout state, product/price context, queued fulfillment evidence, revocation intent records, and protected content readiness.", "Record a non-destructive product access removal intent only after exact confirmation, idempotency, and a current entitlement status check.", "Open /products/entitlements with a checkout intent reference to inspect customer-safe entitlement and fulfillment state.", "Use /offers/source-data and /commerce/source-data to confirm checkout and webhook dependencies before assuming fulfillment exists."]',
  edge_cases_json = '["The seeded product/access catalog is not a complete product admin.", "Public /products/source-data exposes aggregate entitlement, owner-upload, revocation-intent, protected-content, and subscription counts plus redaction flags, not buyer emails, actor emails, raw Stripe IDs, hashes, metadata JSON, private reason notes, R2 keys, signed URLs, or upload bodies.", "Owner-confirmed revocation intents record intent only; they do not remove access, issue refunds, change billing, or notify customers.", "Owner-uploaded private assets are stored as records but are not yet wired to customer delivery.", "Signed object URLs, real protected media, destructive revocation, customer delivery of arbitrary uploads, Customer Portal actions, and live fulfillment automation require future APIs."]',
  agent_access = 'Agents can read /products/source-data, aggregate entitlement inspection counts, the preview route, the customer-safe checkout intent lookup contract, the short-lived private R2-backed download-token boundary with redemption revalidation, the owner-authenticated private asset upload intent boundary, owner-confirmed non-destructive revocation intent evidence, protected content readiness, protected fixture delivery checks, and subscription-backed membership access state. Owner sessions can inspect private buyer entitlement rows, revocation intent records, and protected content readiness in /admin/products, create small private asset upload records, and record non-destructive revocation intents only through exact-confirmed, idempotent, stale-state-checked writes. Trusted paid sandbox webhooks can grant seeded entitlement rows and trusted Stripe Billing webhooks can sync membership access; direct customer delivery of arbitrary uploads, destructive revocation, real protected media delivery, Customer Portal actions, and subscription mutations require later APIs.',
  validation_json = '["Playwright covers /products/source-data, aggregate entitlement inspection redaction, /products/indie-launch-library, customer /products/entitlements lookup, private R2-backed token delivery, current checkout-state revalidation, replay rejection, protected fixture delivery, protected fixture stale-state rejection, subscription-backed membership access activation/inactivation, owner private asset upload intent creation, owner-confirmed non-destructive revocation intent creation, idempotent replay, stale-state rejection, unauthorized rejection, owner /admin/products inspection, revocation intent readiness, protected content readiness, sitemap discovery, and agent manifest read-contract discovery.", "Issue #251 records the first owner-confirmed non-destructive revocation intent write path."]',
  updated_at = unixepoch()
WHERE id = 'journey-publisher-previews-product-access';

UPDATE admin_user_journeys
SET
  issue_numbers_json = '[16,83,99,101,139,141,143,146,147,151,179,181,185,187,251]',
  source_evidence_json = '["https://bumpgrade.com/products/source-data", "https://bumpgrade.com/products/entitlements", "https://bumpgrade.com/api/products/entitlements", "https://bumpgrade.com/api/products/download-tokens", "https://bumpgrade.com/api/products/protected-content", "https://bumpgrade.com/api/admin/products/assets", "https://bumpgrade.com/api/admin/products/revocation-intents", "https://bumpgrade.com/admin/products", "https://bumpgrade.com/commerce/source-data", "https://bumpgrade.com/offers/source-data", "https://github.com/markitics/bumpgrade/issues/16", "https://github.com/markitics/bumpgrade/issues/99", "https://github.com/markitics/bumpgrade/issues/101", "https://github.com/markitics/bumpgrade/issues/139", "https://github.com/markitics/bumpgrade/issues/141", "https://github.com/markitics/bumpgrade/issues/143", "https://github.com/markitics/bumpgrade/issues/146", "https://github.com/markitics/bumpgrade/issues/147", "https://github.com/markitics/bumpgrade/issues/151", "https://github.com/markitics/bumpgrade/issues/179", "https://github.com/markitics/bumpgrade/issues/181", "https://github.com/markitics/bumpgrade/issues/185", "https://github.com/markitics/bumpgrade/issues/187", "https://github.com/markitics/bumpgrade/issues/251"]',
  user_goal = 'Confirm that paid sandbox checkout webhooks can grant product entitlements, trusted Stripe Billing state can sync membership access, queued fulfillment evidence stays public-safe, owner-confirmed revocation intent records stay non-destructive, and protected fixtures return only for active eligible checkout-linked entitlements.',
  happy_path_json = '["Start a sandbox checkout for the primary offer and selected order bump.", "Receive trusted checkout.session.completed webhook evidence.", "Update the checkout intent to paid.", "Insert idempotent product_entitlements rows for mapped line items.", "Queue public-safe fulfillment task evidence without returning signed URLs, R2 object keys, private buyer data, or arbitrary protected content bodies.", "Open /products/entitlements with the checkout intent reference to confirm customer-safe entitlement and fulfillment status.", "Use the bundle entitlement and checkout intent to read a seeded protected course/member fixture through /api/products/protected-content.", "As a verified owner, record a non-destructive product access removal intent with exact confirmation and a current entitlement status check.", "Open /admin/products as a verified owner to inspect the entitlement rows, queued fulfillment evidence, revocation intents, and protected content readiness."]',
  edge_cases_json = '["Duplicate webhook events do not create duplicate entitlements.", "Public /products/source-data exposes aggregate counts and redaction flags, not raw buyer rows.", "Protected fixture delivery rejects mismatched entitlements and stale checkout state.", "Owner-confirmed revocation intents reject stale entitlement status and idempotency conflicts but do not mutate access, billing, refunds, notifications, or fulfillment.", "Signed downloads, arbitrary protected content delivery, customer portal, refunds, destructive revocation, and direct customer delivery of uploads require later confirmed-write APIs.", "Raw Stripe identifiers and buyer email remain server-private."]',
  agent_access = 'Agents can read /products/source-data, /api/products/entitlements, /api/products/download-tokens, /api/products/protected-content, and /commerce/source-data to understand the entitlement grant contract, customer-safe lookup, short-lived private R2-backed fixture delivery with redemption revalidation, owner-upload intent boundary, owner-confirmed non-destructive revocation intent boundary, protected content readiness, protected fixture delivery checks, subscription-backed membership access, and aggregate inspection counts. Owner sessions can inspect private buyer entitlement rows, revocation intent records, and protected content readiness in /admin/products, create small private asset upload records, and record revocation intents via exact-confirmed, idempotent, stale-state-checked writes. Agents cannot grant, destructively revoke, expose private buyer data, deliver arbitrary protected bodies, deliver arbitrary uploads to customers, mutate subscriptions, create Customer Portal sessions, or issue signed object URLs without future authenticated confirmed-write APIs.',
  validation_json = '["Playwright covers source-data output, aggregate redaction, a paid test checkout webhook that creates entitlement rows, customer-safe lookup, private R2-backed token delivery, current checkout-state revalidation, replay rejection, protected fixture delivery and stale-state rejection, subscription-backed membership access activation/inactivation, owner private asset upload intent creation, owner-confirmed non-destructive revocation intent creation, idempotent replay, stale-state rejection, unauthorized rejection, owner /admin/products inspection, revocation intent readiness, protected content readiness, and duplicate webhook idempotency.", "Issue #251 records the owner-confirmed non-destructive revocation intent path."]',
  updated_at = unixepoch()
WHERE id = 'journey-publisher-verifies-sandbox-entitlement-grant';
