CREATE TABLE IF NOT EXISTS analytics_notification_queue_consumer_readiness_records (
  id TEXT PRIMARY KEY,
  dashboard_id TEXT NOT NULL,
  readiness_id TEXT NOT NULL,
  channel_id TEXT NOT NULL,
  inbox_record_id TEXT NOT NULL,
  dispatch_preflight_id TEXT NOT NULL,
  provider_domain_readiness_id TEXT NOT NULL,
  send_payload_readiness_id TEXT NOT NULL,
  queue_producer_readiness_id TEXT NOT NULL,
  record_kind TEXT NOT NULL,
  notification_queue_consumer_readiness_disposition TEXT NOT NULL,
  time_window_key TEXT NOT NULL,
  expected_dashboard_revision_id TEXT NOT NULL,
  expected_readiness_status TEXT NOT NULL,
  expected_notification_inbox_status TEXT NOT NULL,
  expected_notification_dispatch_preflight_status TEXT NOT NULL,
  expected_notification_provider_domain_readiness_status TEXT NOT NULL,
  expected_notification_send_payload_readiness_status TEXT NOT NULL,
  expected_notification_queue_producer_readiness_status TEXT NOT NULL,
  expected_owner_review_status TEXT NOT NULL,
  expected_alert_threshold_count INTEGER NOT NULL DEFAULT 0,
  expected_conversion_sample_size INTEGER NOT NULL DEFAULT 0,
  sample_size_caveat_acknowledged INTEGER NOT NULL DEFAULT 0,
  idempotency_key TEXT NOT NULL,
  actor_user_id TEXT,
  actor_email_hash TEXT NOT NULL,
  private_note_sha256 TEXT,
  confirmation_text_sha256 TEXT NOT NULL,
  owner_queue_consumer_readiness_recorded INTEGER NOT NULL DEFAULT 0,
  queue_binding_reviewed INTEGER NOT NULL DEFAULT 0,
  consumer_mode_reviewed INTEGER NOT NULL DEFAULT 0,
  producer_dependency_reviewed INTEGER NOT NULL DEFAULT 0,
  payload_read_policy_reviewed INTEGER NOT NULL DEFAULT 0,
  ack_policy_reviewed INTEGER NOT NULL DEFAULT 0,
  retry_dead_letter_policy_reviewed INTEGER NOT NULL DEFAULT 0,
  provider_handoff_dependency_reviewed INTEGER NOT NULL DEFAULT 0,
  idempotency_policy_reviewed INTEGER NOT NULL DEFAULT 0,
  backpressure_policy_reviewed INTEGER NOT NULL DEFAULT 0,
  audit_correlation_reviewed INTEGER NOT NULL DEFAULT 0,
  retention_policy_reviewed INTEGER NOT NULL DEFAULT 0,
  email_send_enabled INTEGER NOT NULL DEFAULT 0,
  queue_dispatch_enabled INTEGER NOT NULL DEFAULT 0,
  queue_producer_enabled INTEGER NOT NULL DEFAULT 0,
  queue_consumer_enabled INTEGER NOT NULL DEFAULT 0,
  queue_message_created INTEGER NOT NULL DEFAULT 0,
  queue_message_consumed INTEGER NOT NULL DEFAULT 0,
  queue_message_acknowledged INTEGER NOT NULL DEFAULT 0,
  retry_dead_letter_row_created INTEGER NOT NULL DEFAULT 0,
  queue_payload_body_read INTEGER NOT NULL DEFAULT 0,
  queue_payload_body_created INTEGER NOT NULL DEFAULT 0,
  customer_alert_enabled INTEGER NOT NULL DEFAULT 0,
  traffic_routing_enabled INTEGER NOT NULL DEFAULT 0,
  automated_winner_enabled INTEGER NOT NULL DEFAULT 0,
  revenue_claim_enabled INTEGER NOT NULL DEFAULT 0,
  raw_analytics_rows_exposed INTEGER NOT NULL DEFAULT 0,
  recipient_identity_included INTEGER NOT NULL DEFAULT 0,
  recipient_payload_created INTEGER NOT NULL DEFAULT 0,
  personalized_body_created INTEGER NOT NULL DEFAULT 0,
  raw_payload_body_stored INTEGER NOT NULL DEFAULT 0,
  email_body_included INTEGER NOT NULL DEFAULT 0,
  provider_message_id_included INTEGER NOT NULL DEFAULT 0,
  queue_payload_included INTEGER NOT NULL DEFAULT 0,
  provider_send_enabled INTEGER NOT NULL DEFAULT 0,
  provider_called INTEGER NOT NULL DEFAULT 0,
  provider_configured INTEGER NOT NULL DEFAULT 0,
  provider_response_created INTEGER NOT NULL DEFAULT 0,
  provider_secret_included INTEGER NOT NULL DEFAULT 0,
  sender_domain_configured INTEGER NOT NULL DEFAULT 0,
  sender_domain_verified INTEGER NOT NULL DEFAULT 0,
  sender_credential_included INTEGER NOT NULL DEFAULT 0,
  private_dns_credentials_included INTEGER NOT NULL DEFAULT 0,
  metadata_json TEXT,
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at INTEGER NOT NULL DEFAULT (unixepoch())
);

CREATE UNIQUE INDEX IF NOT EXISTS analytics_notification_queue_consumer_readiness_idempotency_unique
  ON analytics_notification_queue_consumer_readiness_records(idempotency_key);
CREATE INDEX IF NOT EXISTS analytics_notification_queue_consumer_readiness_dashboard_time_idx
  ON analytics_notification_queue_consumer_readiness_records(dashboard_id, created_at);
CREATE INDEX IF NOT EXISTS analytics_notification_queue_consumer_readiness_readiness_channel_idx
  ON analytics_notification_queue_consumer_readiness_records(readiness_id, channel_id, created_at);
CREATE INDEX IF NOT EXISTS analytics_notification_queue_consumer_readiness_send_payload_idx
  ON analytics_notification_queue_consumer_readiness_records(send_payload_readiness_id, created_at);
CREATE INDEX IF NOT EXISTS analytics_notification_queue_consumer_readiness_queue_producer_idx
  ON analytics_notification_queue_consumer_readiness_records(queue_producer_readiness_id, created_at);
