UPDATE admin_roadmap_items
SET
  public_evidence_json = json_array(
    'Tracked by issue #18.',
    'Issue #87 adds the first /analytics/source-data contract and /analytics/indie-launch-dashboard preview scaffold.',
    'Issue #105 adds POST /api/analytics/events with seeded event validation, idempotency, hashed request evidence, and aggregate-only source-data reporting.',
    'Issue #107 adds POST /api/analytics/assignments with seeded experiment validation, deterministic weighted variant assignment, hashed visitor evidence, and aggregate-only assignment reporting.',
    'Issue #119 adds aggregate funnel conversion report rows from captured test events without exposing raw analytics rows.',
    'Issue #121 adds browser-side funnel page-view beacons with server-side bot and preview suppression.',
    'Issue #123 attaches deterministic seeded assignment evidence to captured funnel page views and exposes aggregate variant counts.',
    'Issue #125 attaches normalized UTM/source attribution to captured funnel page views and exposes aggregate source counts.',
    'Issue #127 renders aggregate source attribution rows in the analytics dashboard preview.',
    'Issue #129 adds fixed all-time, 24-hour, 7-day, and 30-day aggregate source and conversion windows to source-data and the dashboard preview.',
    json_object('label', 'Issue #261 owner-confirmed analytics experiment decision evidence', 'url', 'https://github.com/markitics/bumpgrade/issues/261'),
    json_object('label', 'Issue #263 aggregate analytics report export metadata', 'url', 'https://github.com/markitics/bumpgrade/issues/263'),
    json_object('label', 'Issue #265 owner-reviewed analytics cohort comparison evidence', 'url', 'https://github.com/markitics/bumpgrade/issues/265'),
    json_object('label', 'Issue #267 owner-reviewed analytics alert threshold and anomaly-review evidence', 'url', 'https://github.com/markitics/bumpgrade/issues/267'),
    json_object('label', 'Issue #269 owner-reviewed analytics notification delivery readiness evidence', 'url', 'https://github.com/markitics/bumpgrade/issues/269'),
    json_object('label', 'Issue #271 owner-confirmed analytics notification inbox records', 'url', 'https://github.com/markitics/bumpgrade/issues/271'),
    json_object('label', 'Issue #284 owner-confirmed analytics notification dispatch preflights', 'url', 'https://github.com/markitics/bumpgrade/issues/284'),
    json_object('label', 'Issue #286 owner-reviewed analytics notification provider/domain readiness', 'url', 'https://github.com/markitics/bumpgrade/issues/286'),
    json_object('label', 'Issue #288 owner-reviewed analytics notification content/consent readiness', 'url', 'https://github.com/markitics/bumpgrade/issues/288'),
    json_object('label', 'Issue #290 owner-reviewed analytics notification send-payload readiness', 'url', 'https://github.com/markitics/bumpgrade/issues/290'),
    json_object('label', 'Issue #292 owner-reviewed analytics notification queue-producer readiness', 'url', 'https://github.com/markitics/bumpgrade/issues/292'),
    json_object('label', 'Issue #294 owner-reviewed analytics notification queue-consumer readiness', 'url', 'https://github.com/markitics/bumpgrade/issues/294')
  ),
  summary = 'Privacy-safe analytics event capture, session-idempotent funnel page-view beacons with deterministic variant and normalized source attribution evidence, dashboard-visible fixed-window aggregate source breakdowns, deterministic seeded experiment assignment, aggregate funnel conversion reports, aggregate report exports, owner-reviewed cohort comparison evidence, owner-reviewed alert threshold/anomaly-review evidence, owner-reviewed notification delivery readiness evidence, owner-confirmed notification inbox records, owner-confirmed dispatch preflights, owner-reviewed provider/domain readiness records, owner-reviewed content/consent readiness records, owner-reviewed send-payload readiness records, owner-reviewed queue-producer readiness records, owner-reviewed queue-consumer readiness records, owner-confirmed experiment decision evidence, attribution boundaries, and source-linked reporting.',
  next_milestone = 'Add analytics notification provider-call and delivery-attempt readiness only after queue-consumer readiness keeps Queue consumer execution, message consumption, message acknowledgement, retry/dead-letter rows, queue payload body reads, provider responses, provider sends, recipients, email bodies, queues, customer alerts, and sends disabled.',
  updated_at = unixepoch()
WHERE id = 'roadmap-analytics-testing';

UPDATE admin_user_journeys
SET
  issue_numbers_json = json_array(18,87,105,107,119,121,123,125,127,129,261,263,265,267,269,271,284,286,288,290,292,294),
  user_goal = 'Inspect seeded analytics definitions, capture privacy-safe test events, record browser-side funnel page views with deterministic variant and source attribution evidence, read dashboard-visible fixed-window aggregate source rows, assign deterministic variants, read aggregate conversion report rows, read aggregate report export metadata, read owner-reviewed cohort comparison evidence, read owner-reviewed alert threshold/anomaly-review evidence, read owner-reviewed notification delivery readiness evidence, record owner-confirmed notification inbox records, record owner-confirmed dispatch preflights, record owner-reviewed provider/domain readiness evidence, record owner-reviewed content/consent readiness evidence, record owner-reviewed send-payload readiness evidence, record owner-reviewed queue-producer readiness evidence, record owner-reviewed queue-consumer readiness evidence, and record owner-reviewed experiment decision evidence before cookies, contact-level reporting, automated alerts, owner email sends, Queue producer execution, Queue consumer execution, queue dispatch, queue messages, queue message consumption, queue acknowledgements, retry/dead-letter rows, queue payload body reads, queue payload bodies, recipient payloads, personalized bodies, raw payload bodies, provider sends, provider configuration, provider secrets, private DNS credentials, body templates, unsubscribe URLs, customer alerts, traffic routing, automated winners, or revenue claims exist.',
  source_evidence_json = json_array(
    'https://bumpgrade.com/analytics/source-data',
    'https://bumpgrade.com/analytics/indie-launch-dashboard',
    'https://bumpgrade.com/api/analytics/events',
    'https://bumpgrade.com/api/analytics/assignments',
    'https://bumpgrade.com/api/admin/analytics/experiment-decisions',
    'https://bumpgrade.com/api/admin/analytics/notification-inbox-records',
    'https://bumpgrade.com/api/admin/analytics/notification-dispatch-preflights',
    'https://bumpgrade.com/api/admin/analytics/notification-provider-domain-readiness',
    'https://bumpgrade.com/api/admin/analytics/notification-content-consent-readiness',
    'https://bumpgrade.com/api/admin/analytics/notification-send-payload-readiness',
    'https://bumpgrade.com/api/admin/analytics/notification-queue-producer-readiness',
    'https://bumpgrade.com/api/admin/analytics/notification-queue-consumer-readiness',
    'https://bumpgrade.com/admin/analytics',
    'https://bumpgrade.com/funnels/source-data',
    'https://bumpgrade.com/funnels/indie-launch-sandbox',
    'https://github.com/markitics/bumpgrade/issues/18',
    'https://github.com/markitics/bumpgrade/issues/87',
    'https://github.com/markitics/bumpgrade/issues/105',
    'https://github.com/markitics/bumpgrade/issues/107',
    'https://github.com/markitics/bumpgrade/issues/119',
    'https://github.com/markitics/bumpgrade/issues/121',
    'https://github.com/markitics/bumpgrade/issues/123',
    'https://github.com/markitics/bumpgrade/issues/125',
    'https://github.com/markitics/bumpgrade/issues/127',
    'https://github.com/markitics/bumpgrade/issues/129',
    'https://github.com/markitics/bumpgrade/issues/261',
    'https://github.com/markitics/bumpgrade/issues/263',
    'https://github.com/markitics/bumpgrade/issues/265',
    'https://github.com/markitics/bumpgrade/issues/267',
    'https://github.com/markitics/bumpgrade/issues/269',
    'https://github.com/markitics/bumpgrade/issues/271',
    'https://github.com/markitics/bumpgrade/issues/284',
    'https://github.com/markitics/bumpgrade/issues/286',
    'https://github.com/markitics/bumpgrade/issues/288',
    'https://github.com/markitics/bumpgrade/issues/290',
    'https://github.com/markitics/bumpgrade/issues/292',
    'https://github.com/markitics/bumpgrade/issues/294'
  ),
  happy_path_json = json_array(
    'Fetch /analytics/source-data.',
    'Find event IDs, page-view beacon boundary, aggregate source attribution counts, aggregate variant event counts, fixed time windows, metric IDs, aggregate event counts, aggregate conversion report rows, experiment IDs, variant IDs, assignment rule, assignment API, dashboard source section, and write boundary.',
    'Fetch /analytics/source-data?window=24h to inspect public-safe aggregate source and conversion rows for one supported fixed window.',
    'Open /funnels/indie-launch-sandbox with safe UTM parameters and let the session-idempotent page-view beacon assign a variant and record a seeded event with that variant ID and normalized source attribution evidence.',
    'POST a seeded event to /api/analytics/events with an idempotency key and source route.',
    'POST a seeded experiment assignment to /api/analytics/assignments with an anonymous assignment key, idempotency key, and source route.',
    'Read reportExports from /analytics/source-data to inspect aggregate report sections, selected fixed window, sample-size caveats, fixture cohort definitions, owner-reviewed cohort comparison evidence, owner-reviewed alert threshold/anomaly-review evidence, and owner-reviewed notification delivery readiness evidence.',
    'Read notificationInboxRecords from /analytics/source-data to inspect owner-confirmed inbox record counts, current readiness evidence, and redaction flags.',
    'Read notificationDispatchPreflights from /analytics/source-data to inspect owner-confirmed dispatch preflight counts, current inbox evidence, and redaction flags.',
    'Read notificationProviderDomainReadiness from /analytics/source-data to inspect owner-reviewed provider/domain readiness counts, current dispatch-preflight evidence, and redaction flags.',
    'Read notificationContentConsentReadiness from /analytics/source-data to inspect owner-reviewed content/consent readiness counts, current provider/domain evidence, and redaction flags.',
    'Read notificationSendPayloadReadiness from /analytics/source-data to inspect owner-reviewed send-payload readiness counts, current content/consent evidence, and redaction flags.',
    'Read notificationQueueProducerReadiness from /analytics/source-data to inspect owner-reviewed queue-producer readiness counts, current send-payload evidence, and redaction flags.',
    'Read notificationQueueConsumerReadiness from /analytics/source-data to inspect owner-reviewed queue-consumer readiness counts, current queue-producer evidence, and redaction flags.',
    'Open /admin/analytics as a verified owner and record a redacted notification inbox record with the current readiness status, selected fixed-window sample size, threshold count, and sample-size caveat acknowledgement.',
    'Open /admin/analytics as a verified owner and record a redacted dispatch preflight only after a current inbox record exists.',
    'Open /admin/analytics as a verified owner and record redacted provider/domain readiness only after a current dispatch preflight exists.',
    'Open /admin/analytics as a verified owner and record redacted content/consent readiness only after a current provider/domain readiness record exists.',
    'Open /admin/analytics as a verified owner and record redacted send-payload readiness only after a current content/consent readiness record exists.',
    'Open /admin/analytics as a verified owner and record redacted queue-producer readiness only after a current send-payload readiness record exists.',
    'Open /admin/analytics as a verified owner and record redacted queue-consumer readiness only after a current queue-producer readiness record exists.',
    'Open /admin/analytics as a verified owner and record a redacted experiment decision with the current aggregate assignment counts, fixed-window conversion sample size, and sample-size caveat acknowledgement.',
    'Confirm duplicate idempotency returns the same public-safe event or assignment without duplicating rows.',
    'Open /analytics/indie-launch-dashboard to inspect the public preview, aggregate source rows, fixed-window controls, and caveats.'
  ),
  edge_cases_json = json_array(
    'Public source-data exposes aggregate counts, aggregate source attribution counts, aggregate variant counts, fixed-window metadata, report export metadata, owner-reviewed cohort comparison evidence, owner-reviewed alert threshold/anomaly-review evidence, owner-reviewed notification delivery readiness evidence, owner-confirmed notification inbox aggregate evidence, owner-confirmed dispatch preflight aggregate evidence, owner-reviewed provider/domain readiness aggregate evidence, owner-reviewed content/consent readiness aggregate evidence, owner-reviewed send-payload readiness aggregate evidence, owner-reviewed queue-producer readiness aggregate evidence, owner-reviewed queue-consumer readiness aggregate evidence, and conversion rows only, not raw event or assignment rows.',
    'Unsupported event IDs, experiment IDs, source routes, missing idempotency keys, and missing assignment keys return public-safe validation errors.',
    'Bot, crawler, and preview/test-suppressed page-view traffic is ignored before analytics event rows are created.',
    'Cookie assignment, contact-level analytics, raw referrer/query reporting, automated alert sends, owner email sends, Queue producer execution, Queue consumer execution, queue dispatch, queue messages, queue message consumption, queue acknowledgements, retry/dead-letter rows, queue payload body reads, queue payload bodies, recipient payloads, personalized bodies, raw payload bodies, provider sends, provider configuration, provider secrets, private DNS credentials, body templates, unsubscribe URLs, customer alerts, experiment traffic changes, automated winners, and revenue claims remain disabled even after owner decision, cohort comparison evidence, threshold review evidence, notification readiness evidence, notification inbox records, dispatch preflights, provider/domain readiness records, content/consent readiness records, send-payload readiness records, queue-producer readiness records, and queue-consumer readiness records are recorded.',
    'Agents must include sample-size caveats and must not call sparse test events or assignments statistically meaningful.'
  ),
  agent_access = 'Agents can read /analytics/source-data, /analytics/source-data?window=24h, /analytics/indie-launch-dashboard, event capture boundaries, page-view beacon boundaries, dashboard-visible fixed-window aggregate source attribution evidence, aggregate variant evidence, assignment boundaries, aggregate conversion report rows, aggregate report export metadata, owner-reviewed cohort comparison evidence, owner-reviewed alert threshold/anomaly-review evidence, owner-reviewed notification delivery readiness evidence, owner-confirmed notification inbox aggregate evidence, owner-confirmed dispatch preflight aggregate evidence, owner-reviewed provider/domain readiness aggregate evidence, owner-reviewed content/consent readiness aggregate evidence, owner-reviewed send-payload readiness aggregate evidence, owner-reviewed queue-producer readiness aggregate evidence, owner-reviewed queue-consumer readiness aggregate evidence, and redacted experiment decision evidence. Owner sessions can record notification inbox records through /api/admin/analytics/notification-inbox-records, dispatch preflight records through /api/admin/analytics/notification-dispatch-preflights, provider/domain readiness records through /api/admin/analytics/notification-provider-domain-readiness, content/consent readiness records through /api/admin/analytics/notification-content-consent-readiness, send-payload readiness records through /api/admin/analytics/notification-send-payload-readiness, queue-producer readiness records through /api/admin/analytics/notification-queue-producer-readiness, queue-consumer readiness records through /api/admin/analytics/notification-queue-consumer-readiness, and decision evidence through /api/admin/analytics/experiment-decisions. Direct public agent analytics writes, custom events, raw campaign/referrer reporting, raw analytics exports, automated alert sends, owner email sends, provider sends, Queue producer execution, Queue consumer execution, queue dispatch, queue-message creation, queue message consumption, queue acknowledgements, retry/dead-letter rows, queue payload body reads, queue payload body creation, recipient-payload creation, personalized body creation, raw payload body storage, body-template exposure, unsubscribe-URL exposure, customer alerts, experiment routing, automated winners, and revenue claims require future authenticated confirmed-write APIs with privacy review, idempotency, stale-state checks, audit correlation, redaction, retention limits, and sample-size caveats.',
  validation_json = json_array(
    'Playwright covers /analytics/source-data, /analytics/source-data?window=24h, /analytics/indie-launch-dashboard fixed-window source attribution UI, /admin/analytics owner decision, notification inbox, dispatch preflight, provider/domain readiness, content/consent readiness, send-payload readiness, queue-producer readiness, and queue-consumer readiness evidence, aggregate report export metadata, owner-reviewed cohort comparison evidence, owner-reviewed alert threshold/anomaly-review evidence, owner-reviewed notification delivery readiness evidence, owner-confirmed notification inbox evidence, owner-confirmed dispatch preflight evidence, owner-reviewed provider/domain readiness evidence, owner-reviewed content/consent readiness evidence, owner-reviewed send-payload readiness evidence, owner-reviewed queue-producer readiness evidence, owner-reviewed queue-consumer readiness evidence, event ingestion, page-view beacon capture with variant and source attribution evidence, bot suppression, assignment ingestion, conversion reporting from captured events, duplicate idempotency, deterministic assignment, validation failures, opt-in event recording, sitemap discovery, and agent manifest discovery.',
    'Issues #87, #105, #107, #119, #121, #123, #125, #127, #129, #261, #263, #265, #267, #269, #271, #284, #286, #288, #290, #292, and #294 record the analytics source-data scaffold, first privacy-safe event capture path, first deterministic assignment path, first aggregate conversion report, first browser-side funnel page-view beacon, first variant-linked page-view evidence, first aggregate source attribution evidence, first dashboard-visible source breakdown, first fixed-window aggregate filters, first owner-confirmed experiment decision evidence, first aggregate report export metadata, owner-reviewed cohort comparison evidence, owner-reviewed alert threshold/anomaly-review evidence, owner-reviewed notification delivery readiness evidence, owner-confirmed notification inbox records, owner-confirmed dispatch preflights, owner-reviewed provider/domain readiness, owner-reviewed content/consent readiness, owner-reviewed send-payload readiness, owner-reviewed queue-producer readiness, and owner-reviewed queue-consumer readiness.'
  ),
  updated_at = unixepoch()
WHERE id = 'journey-publisher-previews-analytics-experiments';

INSERT INTO admin_work_log_entries (
  id, title, agent_name, agent_kind, session_name, prompt_from_mark, github_issues_json, closed_prs_json,
  features_updated_json, roadmap_updated_json, user_journeys_updated_json, documentation_updated_json,
  validation_json, flags_attention, first_prompt_at, completed_at, relevant_urls_json, pr_comment_url, updated_at
) VALUES (
  'work-log-2026-05-21-analytics-notification-queue-consumer-readiness',
  'Added analytics notification queue-consumer readiness records',
  'Codex',
  'codex',
  'bumpgrade-bootstrap',
  'Continue the Bumpgrade parity build and add owner-reviewed analytics notification queue-consumer readiness evidence for agents.',
  json_array(json_object('number',294,'url','https://github.com/markitics/bumpgrade/issues/294'), json_object('number',18,'url','https://github.com/markitics/bumpgrade/issues/18')),
  json_array(json_object('number',295,'url','https://github.com/markitics/bumpgrade/pull/295')),
  json_array('https://bumpgrade.com/features','https://bumpgrade.com/analytics/source-data'),
  json_array('https://bumpgrade.com/admin/roadmap','https://bumpgrade.com/roadmap/source-data'),
  json_array('https://bumpgrade.com/admin/user-journeys','https://bumpgrade.com/admin/user-journeys/source-data'),
  json_array('src/lib/analytics-notification-queue-consumer-readiness.ts','src/app/api/admin/analytics/notification-queue-consumer-readiness/route.ts','src/app/analytics/source-data/route.ts','src/lib/agent-manifest.ts','docs/features/analytics-experiments.md','drizzle/0113_analytics_notification_queue_consumer_readiness.sql','drizzle/0114_analytics_notification_queue_consumer_admin_surfaces.sql'),
  json_array('npm run db:migrate:local','npm run typecheck','npm run cf:build','npm run lint','npm run test:runtime-secrets','npx playwright test tests/smoke.spec.ts -> 207 passed, 31 skipped','GitHub Actions CI passed for PR #295','npm run db:migrate:remote','npm run deploy -> Worker version cab49acb-9736-4e6e-8196-c3361af7d972','production smoke: screenshot asset 200, /analytics/source-data, /agent-docs/source-data, /features/source-data, /llms.txt, and unauthenticated API redaction'),
  'Queue consumers remain readiness-only: no Cloudflare Queue consumer, Queue message consumption, Queue acknowledgement, retry/dead-letter row, queue payload body read, recipient payload, provider call, provider send, provider response, or provider message ID was enabled.',
  unixepoch(),
  unixepoch(),
  json_array('https://bumpgrade.com/analytics/source-data','https://bumpgrade.com/api/admin/analytics/notification-queue-consumer-readiness','https://bumpgrade.com/agent-docs/source-data','https://bumpgrade.com/pr-screenshots/issue-294-admin-analytics-queue-consumer-readiness.png','https://github.com/markitics/bumpgrade/issues/294','https://github.com/markitics/bumpgrade/pull/295'),
  NULL,
  unixepoch()
)
ON CONFLICT(id) DO UPDATE SET
  title = excluded.title,
  github_issues_json = excluded.github_issues_json,
  closed_prs_json = excluded.closed_prs_json,
  features_updated_json = excluded.features_updated_json,
  roadmap_updated_json = excluded.roadmap_updated_json,
  user_journeys_updated_json = excluded.user_journeys_updated_json,
  documentation_updated_json = excluded.documentation_updated_json,
  validation_json = excluded.validation_json,
  flags_attention = excluded.flags_attention,
  completed_at = excluded.completed_at,
  relevant_urls_json = excluded.relevant_urls_json,
  pr_comment_url = excluded.pr_comment_url,
  updated_at = excluded.updated_at;
