CREATE TABLE IF NOT EXISTS analytics_notification_delivery_status_webhook_readiness_records (
  id TEXT PRIMARY KEY,
  dashboard_id TEXT NOT NULL,
  readiness_id TEXT NOT NULL,
  channel_id TEXT NOT NULL,
  inbox_record_id TEXT NOT NULL,
  dispatch_preflight_id TEXT NOT NULL,
  provider_domain_readiness_id TEXT NOT NULL,
  send_payload_readiness_id TEXT NOT NULL,
  delivery_result_readiness_id TEXT NOT NULL,
  record_kind TEXT NOT NULL,
  notification_delivery_status_webhook_readiness_disposition TEXT NOT NULL,
  time_window_key TEXT NOT NULL,
  expected_dashboard_revision_id TEXT NOT NULL,
  expected_readiness_status TEXT NOT NULL,
  expected_notification_inbox_status TEXT NOT NULL,
  expected_notification_dispatch_preflight_status TEXT NOT NULL,
  expected_notification_provider_domain_readiness_status TEXT NOT NULL,
  expected_notification_send_payload_readiness_status TEXT NOT NULL,
  expected_notification_delivery_result_readiness_status TEXT NOT NULL,
  expected_owner_review_status TEXT NOT NULL,
  expected_alert_threshold_count INTEGER NOT NULL DEFAULT 0,
  expected_conversion_sample_size INTEGER NOT NULL DEFAULT 0,
  sample_size_caveat_acknowledged INTEGER NOT NULL DEFAULT 0,
  idempotency_key TEXT NOT NULL,
  actor_user_id TEXT,
  actor_email_hash TEXT NOT NULL,
  private_note_sha256 TEXT,
  confirmation_text_sha256 TEXT NOT NULL,
  owner_delivery_status_webhook_readiness_recorded INTEGER NOT NULL DEFAULT 0,
  queue_binding_reviewed INTEGER NOT NULL DEFAULT 0,
  consumer_mode_reviewed INTEGER NOT NULL DEFAULT 0,
  producer_dependency_reviewed INTEGER NOT NULL DEFAULT 0,
  payload_read_policy_reviewed INTEGER NOT NULL DEFAULT 0,
  ack_policy_reviewed INTEGER NOT NULL DEFAULT 0,
  retry_dead_letter_policy_reviewed INTEGER NOT NULL DEFAULT 0,
  provider_handoff_dependency_reviewed INTEGER NOT NULL DEFAULT 0,
  idempotency_policy_reviewed INTEGER NOT NULL DEFAULT 0,
  backpressure_policy_reviewed INTEGER NOT NULL DEFAULT 0,
  audit_correlation_reviewed INTEGER NOT NULL DEFAULT 0,
  retention_policy_reviewed INTEGER NOT NULL DEFAULT 0,
  email_send_enabled INTEGER NOT NULL DEFAULT 0,
  queue_dispatch_enabled INTEGER NOT NULL DEFAULT 0,
  queue_producer_enabled INTEGER NOT NULL DEFAULT 0,
  queue_consumer_enabled INTEGER NOT NULL DEFAULT 0,
  delivery_status_webhook_enabled INTEGER NOT NULL DEFAULT 0,
  queue_message_created INTEGER NOT NULL DEFAULT 0,
  queue_message_consumed INTEGER NOT NULL DEFAULT 0,
  queue_message_acknowledged INTEGER NOT NULL DEFAULT 0,
  retry_dead_letter_row_created INTEGER NOT NULL DEFAULT 0,
  queue_payload_body_read INTEGER NOT NULL DEFAULT 0,
  queue_payload_body_created INTEGER NOT NULL DEFAULT 0,
  customer_alert_enabled INTEGER NOT NULL DEFAULT 0,
  traffic_routing_enabled INTEGER NOT NULL DEFAULT 0,
  automated_winner_enabled INTEGER NOT NULL DEFAULT 0,
  revenue_claim_enabled INTEGER NOT NULL DEFAULT 0,
  raw_analytics_rows_exposed INTEGER NOT NULL DEFAULT 0,
  recipient_identity_included INTEGER NOT NULL DEFAULT 0,
  recipient_payload_created INTEGER NOT NULL DEFAULT 0,
  personalized_body_created INTEGER NOT NULL DEFAULT 0,
  raw_payload_body_stored INTEGER NOT NULL DEFAULT 0,
  email_body_included INTEGER NOT NULL DEFAULT 0,
  provider_message_id_included INTEGER NOT NULL DEFAULT 0,
  queue_payload_included INTEGER NOT NULL DEFAULT 0,
  provider_send_enabled INTEGER NOT NULL DEFAULT 0,
  delivery_status_webhook_recorded INTEGER NOT NULL DEFAULT 0,
  provider_configured INTEGER NOT NULL DEFAULT 0,
  provider_response_created INTEGER NOT NULL DEFAULT 0,
  provider_secret_included INTEGER NOT NULL DEFAULT 0,
  sender_domain_configured INTEGER NOT NULL DEFAULT 0,
  sender_domain_verified INTEGER NOT NULL DEFAULT 0,
  sender_credential_included INTEGER NOT NULL DEFAULT 0,
  private_dns_credentials_included INTEGER NOT NULL DEFAULT 0,
  metadata_json TEXT,
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at INTEGER NOT NULL DEFAULT (unixepoch())
);

CREATE UNIQUE INDEX IF NOT EXISTS analytics_notification_delivery_status_webhook_readiness_idempotency_unique
  ON analytics_notification_delivery_status_webhook_readiness_records(idempotency_key);
CREATE INDEX IF NOT EXISTS analytics_notification_delivery_status_webhook_readiness_dashboard_time_idx
  ON analytics_notification_delivery_status_webhook_readiness_records(dashboard_id, created_at);
CREATE INDEX IF NOT EXISTS analytics_notification_delivery_status_webhook_readiness_readiness_channel_idx
  ON analytics_notification_delivery_status_webhook_readiness_records(readiness_id, channel_id, created_at);
CREATE INDEX IF NOT EXISTS analytics_notification_delivery_status_webhook_readiness_send_payload_idx
  ON analytics_notification_delivery_status_webhook_readiness_records(send_payload_readiness_id, created_at);
CREATE INDEX IF NOT EXISTS analytics_notification_delivery_status_webhook_readiness_delivery_result_idx
  ON analytics_notification_delivery_status_webhook_readiness_records(delivery_result_readiness_id, created_at);

UPDATE admin_roadmap_items
SET
  public_evidence_json = json_array(
    'Tracked by issue #18.',
    'Issue #87 adds the first /analytics/source-data contract and /analytics/indie-launch-dashboard preview scaffold.',
    'Issue #105 adds POST /api/analytics/events with seeded event validation, idempotency, hashed request evidence, and aggregate-only source-data reporting.',
    'Issue #107 adds POST /api/analytics/assignments with seeded experiment validation, deterministic weighted variant assignment, hashed visitor evidence, and aggregate-only assignment reporting.',
    'Issue #119 adds aggregate funnel conversion report rows from captured test events without exposing raw analytics rows.',
    'Issue #121 adds browser-side funnel page-view beacons with server-side bot and preview suppression.',
    'Issue #123 attaches deterministic seeded assignment evidence to captured funnel page views and exposes aggregate variant counts.',
    'Issue #125 attaches normalized UTM/source attribution to captured funnel page views and exposes aggregate source counts.',
    'Issue #127 renders aggregate source attribution rows in the analytics dashboard preview.',
    'Issue #129 adds fixed all-time, 24-hour, 7-day, and 30-day aggregate source and conversion windows to source-data and the dashboard preview.',
    json_object('label', 'Issue #261 owner-confirmed analytics experiment decision evidence', 'url', 'https://github.com/markitics/bumpgrade/issues/261'),
    json_object('label', 'Issue #263 aggregate analytics report export metadata', 'url', 'https://github.com/markitics/bumpgrade/issues/263'),
    json_object('label', 'Issue #265 owner-reviewed analytics cohort comparison evidence', 'url', 'https://github.com/markitics/bumpgrade/issues/265'),
    json_object('label', 'Issue #267 owner-reviewed analytics alert threshold and anomaly-review evidence', 'url', 'https://github.com/markitics/bumpgrade/issues/267'),
    json_object('label', 'Issue #269 owner-reviewed analytics notification delivery readiness evidence', 'url', 'https://github.com/markitics/bumpgrade/issues/269'),
    json_object('label', 'Issue #271 owner-confirmed analytics notification inbox records', 'url', 'https://github.com/markitics/bumpgrade/issues/271'),
    json_object('label', 'Issue #284 owner-confirmed analytics notification dispatch preflights', 'url', 'https://github.com/markitics/bumpgrade/issues/284'),
    json_object('label', 'Issue #286 owner-reviewed analytics notification provider/domain readiness', 'url', 'https://github.com/markitics/bumpgrade/issues/286'),
    json_object('label', 'Issue #288 owner-reviewed analytics notification content/consent readiness', 'url', 'https://github.com/markitics/bumpgrade/issues/288'),
    json_object('label', 'Issue #290 owner-reviewed analytics notification send-payload readiness', 'url', 'https://github.com/markitics/bumpgrade/issues/290'),
    json_object('label', 'Issue #292 owner-reviewed analytics notification queue-producer readiness', 'url', 'https://github.com/markitics/bumpgrade/issues/292'),
    json_object('label', 'Issue #294 owner-reviewed analytics notification queue-consumer readiness', 'url', 'https://github.com/markitics/bumpgrade/issues/294'),
    json_object('label', 'Issue #297 owner-reviewed analytics notification provider-call readiness', 'url', 'https://github.com/markitics/bumpgrade/issues/297'),
    json_object('label', 'Issue #299 owner-reviewed analytics notification delivery-attempt readiness', 'url', 'https://github.com/markitics/bumpgrade/issues/299'),
    json_object('label', 'Issue #301 owner-reviewed analytics notification delivery-result readiness', 'url', 'https://github.com/markitics/bumpgrade/issues/301'),
    json_object('label', 'Issue #303 owner-reviewed analytics notification delivery-status-webhook readiness', 'url', 'https://github.com/markitics/bumpgrade/issues/303')
  ),
  summary = 'Privacy-safe analytics event capture, session-idempotent funnel page-view beacons with deterministic variant and normalized source attribution evidence, dashboard-visible fixed-window aggregate source breakdowns, deterministic seeded experiment assignment, aggregate funnel conversion reports, aggregate report exports, owner-reviewed cohort comparison evidence, owner-reviewed alert threshold/anomaly-review evidence, owner-reviewed notification delivery readiness evidence, owner-confirmed notification inbox records, owner-confirmed dispatch preflights, owner-reviewed provider/domain readiness records, owner-reviewed content/consent readiness records, owner-reviewed send-payload readiness records, owner-reviewed queue-producer readiness records, owner-reviewed queue-consumer readiness records, owner-reviewed provider-call readiness records, owner-reviewed delivery-attempt readiness records, owner-reviewed delivery-result readiness records, owner-reviewed delivery-status-webhook readiness records, owner-confirmed experiment decision evidence, attribution boundaries, and source-linked reporting.',
  next_milestone = 'Add analytics notification provider-polling readiness only after delivery-status-webhook readiness keeps provider sends/calls, provider responses, provider message IDs, delivery receipts, status webhooks, provider polling, provider secrets, sender credentials, recipients, email bodies, queues, customer alerts, and sends disabled.',
  updated_at = unixepoch()
WHERE id = 'roadmap-analytics-testing';

UPDATE admin_user_journeys
SET
  issue_numbers_json = json_array(18,87,105,107,119,121,123,125,127,129,261,263,265,267,269,271,284,286,288,290,292,294,297,299,301,303),
  user_goal = 'Inspect seeded analytics definitions, capture privacy-safe test events, record browser-side funnel page views with deterministic variant and source attribution evidence, read dashboard-visible fixed-window aggregate source rows, assign deterministic variants, read aggregate conversion report rows, read aggregate report export metadata, read owner-reviewed cohort comparison evidence, read owner-reviewed alert threshold/anomaly-review evidence, read owner-reviewed notification delivery readiness evidence, record owner-confirmed notification inbox records, record owner-confirmed dispatch preflights, record owner-reviewed provider/domain readiness evidence, record owner-reviewed content/consent readiness evidence, record owner-reviewed send-payload readiness evidence, record owner-reviewed queue-producer readiness evidence, record owner-reviewed queue-consumer readiness evidence, record owner-reviewed provider-call readiness evidence, record owner-reviewed delivery-attempt readiness evidence, record owner-reviewed delivery-result readiness evidence, record owner-reviewed delivery-status-webhook readiness evidence, and record owner-reviewed experiment decision evidence before cookies, contact-level reporting, automated alerts, owner email sends, Queue producer execution, Queue consumer execution, provider calls, delivery attempts, delivery results, delivery status webhooks, provider responses, provider message IDs, delivery receipts, receipt payloads, status webhooks, provider polling, queue dispatch, queue messages, queue message consumption, queue acknowledgements, retry/dead-letter rows, queue payload body reads, queue payload bodies, recipient payloads, personalized bodies, raw payload bodies, provider sends, provider configuration, provider secrets, sender credentials, private DNS credentials, body templates, unsubscribe URLs, customer alerts, traffic routing, automated winners, or revenue claims exist.',
  source_evidence_json = json_array(
    'https://bumpgrade.com/analytics/source-data',
    'https://bumpgrade.com/analytics/indie-launch-dashboard',
    'https://bumpgrade.com/api/analytics/events',
    'https://bumpgrade.com/api/analytics/assignments',
    'https://bumpgrade.com/api/admin/analytics/experiment-decisions',
    'https://bumpgrade.com/api/admin/analytics/notification-inbox-records',
    'https://bumpgrade.com/api/admin/analytics/notification-dispatch-preflights',
    'https://bumpgrade.com/api/admin/analytics/notification-provider-domain-readiness',
    'https://bumpgrade.com/api/admin/analytics/notification-content-consent-readiness',
    'https://bumpgrade.com/api/admin/analytics/notification-send-payload-readiness',
    'https://bumpgrade.com/api/admin/analytics/notification-queue-producer-readiness',
    'https://bumpgrade.com/api/admin/analytics/notification-queue-consumer-readiness',
    'https://bumpgrade.com/api/admin/analytics/notification-provider-call-readiness',
    'https://bumpgrade.com/api/admin/analytics/notification-delivery-attempt-readiness',
    'https://bumpgrade.com/api/admin/analytics/notification-delivery-result-readiness',
    'https://bumpgrade.com/api/admin/analytics/notification-delivery-status-webhook-readiness',
    'https://bumpgrade.com/admin/analytics',
    'https://bumpgrade.com/funnels/source-data',
    'https://bumpgrade.com/funnels/indie-launch-sandbox',
    'https://github.com/markitics/bumpgrade/issues/18',
    'https://github.com/markitics/bumpgrade/issues/87',
    'https://github.com/markitics/bumpgrade/issues/105',
    'https://github.com/markitics/bumpgrade/issues/107',
    'https://github.com/markitics/bumpgrade/issues/119',
    'https://github.com/markitics/bumpgrade/issues/121',
    'https://github.com/markitics/bumpgrade/issues/123',
    'https://github.com/markitics/bumpgrade/issues/125',
    'https://github.com/markitics/bumpgrade/issues/127',
    'https://github.com/markitics/bumpgrade/issues/129',
    'https://github.com/markitics/bumpgrade/issues/261',
    'https://github.com/markitics/bumpgrade/issues/263',
    'https://github.com/markitics/bumpgrade/issues/265',
    'https://github.com/markitics/bumpgrade/issues/267',
    'https://github.com/markitics/bumpgrade/issues/269',
    'https://github.com/markitics/bumpgrade/issues/271',
    'https://github.com/markitics/bumpgrade/issues/284',
    'https://github.com/markitics/bumpgrade/issues/286',
    'https://github.com/markitics/bumpgrade/issues/288',
    'https://github.com/markitics/bumpgrade/issues/290',
    'https://github.com/markitics/bumpgrade/issues/292',
    'https://github.com/markitics/bumpgrade/issues/294',
    'https://github.com/markitics/bumpgrade/issues/297',
    'https://github.com/markitics/bumpgrade/issues/299',
    'https://github.com/markitics/bumpgrade/issues/301',
    'https://github.com/markitics/bumpgrade/issues/303'
  ),
  happy_path_json = json_array(
    'Fetch /analytics/source-data.',
    'Find event IDs, page-view beacon boundary, aggregate source attribution counts, aggregate variant event counts, fixed time windows, metric IDs, aggregate event counts, aggregate conversion report rows, experiment IDs, variant IDs, assignment rule, assignment API, dashboard source section, and write boundary.',
    'Fetch /analytics/source-data?window=24h to inspect public-safe aggregate source and conversion rows for one supported fixed window.',
    'Open /funnels/indie-launch-sandbox with safe UTM parameters and let the session-idempotent page-view beacon assign a variant and record a seeded event with that variant ID and normalized source attribution evidence.',
    'POST a seeded event to /api/analytics/events with an idempotency key and source route.',
    'POST a seeded experiment assignment to /api/analytics/assignments with an anonymous assignment key, idempotency key, and source route.',
    'Read notificationProviderCallReadiness from /analytics/source-data to inspect owner-reviewed provider-call readiness counts, current queue-consumer evidence, and redaction flags.',
    'Read notificationDeliveryAttemptReadiness from /analytics/source-data to inspect owner-reviewed delivery-attempt readiness counts, current provider-call evidence, and redaction flags.',
    'Read notificationDeliveryResultReadiness from /analytics/source-data to inspect owner-reviewed delivery-result readiness counts, current delivery-attempt evidence, and redaction flags.',
    'Read notificationDeliveryStatusWebhookReadiness from /analytics/source-data to inspect owner-reviewed delivery-status-webhook readiness counts, current delivery-result evidence, and redaction flags.',
    'Open /admin/analytics as a verified owner and record redacted queue-consumer readiness only after a current queue-producer readiness record exists.',
    'Open /admin/analytics as a verified owner and record redacted provider-call readiness only after a current queue-consumer readiness record exists.',
    'Open /admin/analytics as a verified owner and record redacted delivery-attempt readiness only after a current provider-call readiness record exists.',
    'Open /admin/analytics as a verified owner and record redacted delivery-result readiness only after a current delivery-attempt readiness record exists.',
    'Open /admin/analytics as a verified owner and record redacted delivery-status-webhook readiness only after a current delivery-result readiness record exists.',
    'Open /admin/analytics as a verified owner and record a redacted experiment decision with the current aggregate assignment counts, fixed-window conversion sample size, and sample-size caveat acknowledgement.',
    'Confirm duplicate idempotency returns the same public-safe event or assignment without duplicating rows.',
    'Open /analytics/indie-launch-dashboard to inspect the public preview, aggregate source rows, fixed-window controls, and caveats.'
  ),
  edge_cases_json = json_array(
    'Public source-data exposes aggregate counts, aggregate source attribution counts, aggregate variant counts, fixed-window metadata, report export metadata, owner-reviewed cohort comparison evidence, owner-reviewed alert threshold/anomaly-review evidence, owner-reviewed notification delivery readiness evidence, owner-confirmed notification inbox aggregate evidence, owner-confirmed dispatch preflight aggregate evidence, owner-reviewed provider/domain readiness aggregate evidence, owner-reviewed content/consent readiness aggregate evidence, owner-reviewed send-payload readiness aggregate evidence, owner-reviewed queue-producer readiness aggregate evidence, owner-reviewed queue-consumer readiness aggregate evidence, owner-reviewed provider-call readiness aggregate evidence, owner-reviewed delivery-attempt readiness aggregate evidence, owner-reviewed delivery-result readiness aggregate evidence, owner-reviewed delivery-status-webhook readiness aggregate evidence, and conversion rows only, not raw event or assignment rows.',
    'Unsupported event IDs, experiment IDs, source routes, missing idempotency keys, and missing assignment keys return public-safe validation errors.',
    'Cookie assignment, contact-level analytics, raw referrer/query reporting, automated alert sends, owner email sends, Queue producer execution, Queue consumer execution, provider calls, delivery attempts, delivery results, delivery status webhooks, status webhooks, provider polling, queue dispatch, queue messages, queue message consumption, queue acknowledgements, retry/dead-letter rows, queue payload body reads, queue payload bodies, recipient payloads, personalized bodies, raw payload bodies, provider sends, provider responses, provider message IDs, delivery receipts, receipt payloads, provider configuration, provider secrets, sender credentials, private DNS credentials, body templates, unsubscribe URLs, customer alerts, experiment traffic changes, automated winners, and revenue claims remain disabled even after owner decision, cohort comparison evidence, threshold review evidence, notification readiness evidence, notification inbox records, dispatch preflights, provider/domain readiness records, content/consent readiness records, send-payload readiness records, queue-producer readiness records, queue-consumer readiness records, provider-call readiness records, delivery-attempt readiness records, delivery-result readiness records, and delivery-status-webhook readiness records are recorded.',
    'Agents must include sample-size caveats and must not call sparse test events or assignments statistically meaningful.'
  ),
  agent_access = 'Agents can read /analytics/source-data, /analytics/source-data?window=24h, /analytics/indie-launch-dashboard, event capture boundaries, page-view beacon boundaries, dashboard-visible fixed-window aggregate source attribution evidence, aggregate variant evidence, assignment boundaries, aggregate conversion report rows, aggregate report export metadata, owner-reviewed cohort comparison evidence, owner-reviewed alert threshold/anomaly-review evidence, owner-reviewed notification delivery readiness evidence, owner-confirmed notification inbox aggregate evidence, owner-confirmed dispatch preflight aggregate evidence, owner-reviewed provider/domain readiness aggregate evidence, owner-reviewed content/consent readiness aggregate evidence, owner-reviewed send-payload readiness aggregate evidence, owner-reviewed queue-producer readiness aggregate evidence, owner-reviewed queue-consumer readiness aggregate evidence, owner-reviewed provider-call readiness aggregate evidence, owner-reviewed delivery-attempt readiness aggregate evidence, owner-reviewed delivery-result readiness aggregate evidence, owner-reviewed delivery-status-webhook readiness aggregate evidence, and redacted experiment decision evidence. Owner sessions can record notification inbox records through /api/admin/analytics/notification-inbox-records, dispatch preflight records through /api/admin/analytics/notification-dispatch-preflights, provider/domain readiness records through /api/admin/analytics/notification-provider-domain-readiness, content/consent readiness records through /api/admin/analytics/notification-content-consent-readiness, send-payload readiness records through /api/admin/analytics/notification-send-payload-readiness, queue-producer readiness records through /api/admin/analytics/notification-queue-producer-readiness, queue-consumer readiness records through /api/admin/analytics/notification-queue-consumer-readiness, provider-call readiness records through /api/admin/analytics/notification-provider-call-readiness, delivery-attempt readiness records through /api/admin/analytics/notification-delivery-attempt-readiness, delivery-result readiness records through /api/admin/analytics/notification-delivery-result-readiness, delivery-status-webhook readiness records through /api/admin/analytics/notification-delivery-status-webhook-readiness, and decision evidence through /api/admin/analytics/experiment-decisions. Direct public agent analytics writes, custom events, raw campaign/referrer reporting, raw analytics exports, automated alert sends, owner email sends, provider sends, provider calls, delivery attempts, delivery results, delivery status webhooks, provider responses, provider message IDs, delivery receipts, receipt payloads, status webhooks, provider polling, provider configuration, provider secrets, sender credentials, private DNS credentials, Queue producer execution, Queue consumer execution, queue dispatch, queue-message creation, queue message consumption, queue acknowledgements, retry/dead-letter rows, queue payload body reads, queue payload body creation, recipient-payload creation, personalized body creation, raw payload body storage, body-template exposure, unsubscribe-URL exposure, customer alerts, experiment routing, automated winners, and revenue claims require future authenticated confirmed-write APIs with privacy review, idempotency, stale-state checks, audit correlation, redaction, retention limits, and sample-size caveats.',
  validation_json = json_array(
    'Playwright covers /analytics/source-data, /analytics/source-data?window=24h, /analytics/indie-launch-dashboard fixed-window source attribution UI, /admin/analytics owner decision, notification inbox, dispatch preflight, provider/domain readiness, content/consent readiness, send-payload readiness, queue-producer readiness, queue-consumer readiness, provider-call readiness, delivery-attempt readiness, delivery-result readiness, and delivery-status-webhook readiness evidence, aggregate report export metadata, owner-reviewed cohort comparison evidence, owner-reviewed alert threshold/anomaly-review evidence, owner-reviewed notification delivery readiness evidence, owner-confirmed notification inbox evidence, owner-confirmed dispatch preflight evidence, owner-reviewed provider/domain readiness evidence, owner-reviewed content/consent readiness evidence, owner-reviewed send-payload readiness evidence, owner-reviewed queue-producer readiness evidence, owner-reviewed queue-consumer readiness evidence, owner-reviewed provider-call readiness evidence, owner-reviewed delivery-attempt readiness evidence, owner-reviewed delivery-result readiness evidence, owner-reviewed delivery-status-webhook readiness evidence, event ingestion, page-view beacon capture with variant and source attribution evidence, bot suppression, assignment ingestion, conversion reporting from captured events, duplicate idempotency, deterministic assignment, validation failures, opt-in event recording, sitemap discovery, and agent manifest discovery.',
    'Issues #87, #105, #107, #119, #121, #123, #125, #127, #129, #261, #263, #265, #267, #269, #271, #284, #286, #288, #290, #292, #294, #297, #299, #301, and #303 record the analytics source-data scaffold, first privacy-safe event capture path, first deterministic assignment path, first aggregate conversion report, first browser-side funnel page-view beacon, first variant-linked page-view evidence, first aggregate source attribution evidence, first dashboard-visible source breakdown, first fixed-window aggregate filters, first owner-confirmed experiment decision evidence, first aggregate report export metadata, owner-reviewed cohort comparison evidence, owner-reviewed alert threshold/anomaly-review evidence, owner-reviewed notification delivery readiness evidence, owner-confirmed notification inbox records, owner-confirmed dispatch preflights, owner-reviewed provider/domain readiness, owner-reviewed content/consent readiness, owner-reviewed send-payload readiness, owner-reviewed queue-producer readiness, owner-reviewed queue-consumer readiness, owner-reviewed provider-call readiness, owner-reviewed delivery-attempt readiness, owner-reviewed delivery-result readiness, and owner-reviewed delivery-status-webhook readiness.'
  ),
  updated_at = unixepoch()
WHERE id = 'journey-publisher-previews-analytics-experiments';

INSERT INTO admin_work_log_entries (
  id, title, agent_name, agent_kind, session_name, prompt_from_mark, github_issues_json, closed_prs_json,
  features_updated_json, roadmap_updated_json, user_journeys_updated_json, documentation_updated_json,
  validation_json, flags_attention, first_prompt_at, completed_at, relevant_urls_json, pr_comment_url, updated_at
) VALUES (
  'work-log-2026-05-21-analytics-notification-delivery-status-webhook-readiness',
  'Added analytics notification delivery-status-webhook readiness records',
  'Codex',
  'codex',
  'bumpgrade-bootstrap',
  'Continue the Bumpgrade parity build and add owner-reviewed analytics notification delivery-status-webhook readiness evidence for agents.',
  json_array(json_object('number',303,'url','https://github.com/markitics/bumpgrade/issues/303'), json_object('number',18,'url','https://github.com/markitics/bumpgrade/issues/18')),
  json_array(),
  json_array('https://bumpgrade.com/features','https://bumpgrade.com/analytics/source-data'),
  json_array('https://bumpgrade.com/admin/roadmap','https://bumpgrade.com/roadmap/source-data'),
  json_array('https://bumpgrade.com/admin/user-journeys','https://bumpgrade.com/admin/user-journeys/source-data'),
  json_array('src/lib/analytics-notification-delivery-status-webhook-readiness.ts','src/app/api/admin/analytics/notification-delivery-status-webhook-readiness/route.ts','src/app/analytics/source-data/route.ts','src/lib/agent-manifest.ts','docs/features/analytics-experiments.md','docs/agent/agent-ready.md','drizzle/0118_analytics_notification_delivery_status_webhook_readiness.sql'),
  json_array('npm run db:migrate:local','npm run typecheck','npm run cf:build','npm run lint','npm run test:runtime-secrets','npx playwright test tests/smoke.spec.ts --project=chromium -> 118 passed, 1 skipped','focused analytics delivery-status-webhook readiness, source-data, agent docs, admin source-data, and user-journey smoke tests','admin analytics delivery-status-webhook readiness screenshot captured under docs/pr-screenshots and public/pr-screenshots'),
  'Delivery-status webhook readiness remains review-only: no provider send or call, delivery result, delivery status webhook, status webhook, provider polling, provider configuration, provider response, provider message ID, delivery receipt, receipt payload, provider secret, sender credential, private DNS credential, Queue producer, queue message, queue acknowledgement, queue payload body, recipient payload, email body, customer alert, traffic routing, automated winner, or revenue claim was enabled.',
  unixepoch(),
  unixepoch(),
  json_array('https://bumpgrade.com/analytics/source-data','https://bumpgrade.com/api/admin/analytics/notification-delivery-status-webhook-readiness','https://bumpgrade.com/agent-docs/source-data','https://bumpgrade.com/pr-screenshots/issue-303-admin-analytics-delivery-status-webhook-readiness.png','https://github.com/markitics/bumpgrade/issues/303'),
  NULL,
  unixepoch()
)
ON CONFLICT(id) DO UPDATE SET
  title = excluded.title,
  github_issues_json = excluded.github_issues_json,
  closed_prs_json = excluded.closed_prs_json,
  features_updated_json = excluded.features_updated_json,
  roadmap_updated_json = excluded.roadmap_updated_json,
  user_journeys_updated_json = excluded.user_journeys_updated_json,
  documentation_updated_json = excluded.documentation_updated_json,
  validation_json = excluded.validation_json,
  flags_attention = excluded.flags_attention,
  completed_at = excluded.completed_at,
  relevant_urls_json = excluded.relevant_urls_json,
  pr_comment_url = excluded.pr_comment_url,
  updated_at = excluded.updated_at;
