UPDATE admin_roadmap_items
SET
  status = 'active',
  summary = 'Multi-step funnel model, source-data contract, read-only seeded preview scaffold, owner-gated editable draft scaffold with step edit/reorder controls, owner-gated private preview, exact-confirmed public publishing, reusable template and block-template library records including webinar/resource page shapes, owner-confirmed template-to-draft creation, owner-confirmed private draft duplication, owner-confirmed checkout-offer linking on private draft steps, public sandbox checkout start rendering from published linked checkout blocks, owner-confirmed archive/unpublish lifecycle actions, and safe draft proposals.',
  public_evidence_json = '["Tracked by issue #14.", "Issue #79 adds the first /funnels/source-data contract and /funnels/indie-launch-sandbox preview scaffold.", "Issue #91 adds owner-gated /admin/funnels, /api/admin/funnels/drafts, and D1 draft/audit tables.", "Issue #93 adds owner-gated step title, goal, kind, and order editing on private D1 drafts.", "Issue #95 adds owner-gated private draft preview from current D1 draft state.", "Issue #135 adds exact-confirmed public publishing from D1 draft funnels to stable public /funnels/{slug} routes.", "Issue #159 adds reusable funnel templates and block-template library records to /funnels/source-data and the seeded preview route.", "Issue #161 adds owner-confirmed template-to-draft creation from reusable funnel templates.", "Issue #163 adds owner-confirmed checkout-offer linking to private draft checkout blocks.", "Issue #165 adds public sandbox checkout start rendering on published funnel checkout blocks with owner-confirmed checkout links.", "Issue #213 adds webinar and resource funnel template/block contracts plus D1 step-kind storage readiness.", "Issue #215 adds owner-confirmed private draft duplication with checkout-link metadata stripped by default.", "Issue #341 adds owner-confirmed archive/unpublish lifecycle actions that preserve audit evidence and remove published routes from source data."]',
  next_milestone = 'Add physical deletion policy, drag-and-drop block editing, live webinar integrations, private resource delivery, live checkout rollout, and direct agent-safe edit/duplicate/archive tools on top of D1 draft funnels.',
  mark_attention = NULL,
  updated_at = unixepoch()
WHERE id = 'roadmap-funnels';

UPDATE admin_user_journeys
SET
  title = 'Owner seeds, edits, previews, publishes, and archives a draft funnel',
  issue_numbers_json = '[14,79,91,93,95,135,159,161,163,165,213,215,341]',
  source_evidence_json = '["https://bumpgrade.com/admin/funnels","https://bumpgrade.com/admin/funnels/funnel-draft-indie-launch-working-copy/preview","https://bumpgrade.com/funnels/indie-launch-working-copy","https://bumpgrade.com/funnels/source-data","https://github.com/markitics/bumpgrade/issues/14","https://github.com/markitics/bumpgrade/issues/91","https://github.com/markitics/bumpgrade/issues/93","https://github.com/markitics/bumpgrade/issues/95","https://github.com/markitics/bumpgrade/issues/135","https://github.com/markitics/bumpgrade/issues/159","https://github.com/markitics/bumpgrade/issues/161","https://github.com/markitics/bumpgrade/issues/163","https://github.com/markitics/bumpgrade/issues/165","https://github.com/markitics/bumpgrade/issues/213","https://github.com/markitics/bumpgrade/issues/215","https://github.com/markitics/bumpgrade/issues/341"]',
  user_goal = 'Create, seed, template-start, or duplicate an owner-gated draft funnel, including webinar and resource page shapes, tune the ordered steps, attach the seeded sandbox checkout offer to a checkout block, preview it privately, publish it to a public route that can start the linked sandbox checkout after exact confirmation, then archive or unpublish without deleting evidence.',
  happy_path_json = '["Sign in with an allowlisted owner account.","Open /admin/funnels.","Seed the indie launch working draft, create a generic draft, or create a private draft from a reusable template after typing the exact template confirmation text.","Create webinar registration/replay or resource-library private drafts from the reusable templates when those page shapes fit the offer.","Duplicate an existing private draft after typing the exact duplicate confirmation text and using the current draft revision.","Edit a step title, goal, or kind, then move a step up or down.","Attach the seeded sandbox checkout offer to a draft checkout block after typing the exact checkout-link confirmation text and using the current draft revision.","Open the owner-gated preview route to confirm the private draft sequence reflects current D1 state.","Type the exact publish confirmation text with the current revision and publish the draft.","Open the public /funnels/{slug} route and confirm the published sequence is crawlable and the linked checkout block renders the sandbox checkout start panel.","Type the exact archive confirmation text with the current revision and archive or unpublish the draft.","Use /funnels/source-data to confirm archived drafts and unpublished public routes are excluded from published D1 funnel summaries."]',
  edge_cases_json = '["The admin draft builder is owner-gated and unpublished draft copy is not crawlable public content.","Template-to-draft creation writes only private D1 draft rows and audit metadata; it does not publish.","Draft duplication writes only a new private D1 draft, copies ordered steps and blocks, strips checkout-link metadata, and does not publish.","Webinar/resource templates are page shapes only; they do not create webinar provider state, reminder sequences, replay hosting, private files, signed URLs, or entitlements.","Checkout-offer linking writes public-safe metadata into private draft step blocks and does not start a checkout session or enable live billing by itself.","The public linked checkout start remains sandbox-only, exact-confirmed, idempotent, and constrained to the seeded offer stack.","Publishing and archive/unpublish actions require exact confirmation and a fresh revision ID.","Archiving changes status to archived, clears preview_route, and preserves draft, step, block, checkout-link, and audit records; it does not physically delete data.","Checkout-link deletion, physical deletion, drag-and-drop layout editing, live billing, direct agent duplication, and direct agent writes still require future confirmed-write APIs.","/funnels/source-data lists published D1 funnels but does not expose raw owner session or unpublished or archived private draft data."]',
  agent_access = 'Agents can read public /funnels/source-data, seeded funnel routes, reusable templates including webinar/resource page shapes, draft duplication capability metadata, checkout-link capability metadata, public funnel checkout-start capability metadata, archive/unpublish lifecycle metadata, and published D1 funnel routes. Owner-session UI may create from templates, duplicate, edit, link checkout offers, preview, publish, archive, and unpublish private draft steps with actor identity, confirmation, idempotency, audit correlation, stale-state checks, and redaction; direct agent edit/duplicate/archive tools are still planned.',
  validation_json = '["Playwright covers the owner-gated /admin/funnels surface, webinar/resource template records, template-to-draft create path, draft duplicate path, checkout-link create path, idempotent replay, stale checkout-link rejection, seed/update/reorder/publish/archive POST paths, stale publish/archive rejection, private draft preview, public D1 funnel route rendering, public linked-checkout start rendering, archive removal from /funnels/source-data, /funnels/source-data capability metadata, and agent manifest discovery.","Issue #91 records the first owner-gated draft funnel builder scaffold.","Issue #93 records the first step edit and reorder controls.","Issue #95 records the first owner-gated private draft preview route.","Issue #135 records the first exact-confirmed D1 draft publishing path.","Issue #159 records reusable template and block-template source data.","Issue #161 records owner-confirmed template-to-draft creation.","Issue #163 records owner-confirmed checkout-offer linking on private draft steps.","Issue #165 records public sandbox checkout start rendering on published linked checkout blocks.","Issue #213 records webinar/resource template and block contracts.","Issue #215 records owner-confirmed private draft duplication.","Issue #341 records owner-confirmed archive/unpublish lifecycle actions."]',
  updated_at = unixepoch()
WHERE id = 'journey-owner-seeds-editable-draft-funnel';
